### PR TITLE
Sharpen the corners

### PR DESCRIPTION
**Pull request by benlk**
This removes every last vestige of rounded corners, with the exception of the round facings on the footer social media buttons.

For #777

### CODE REVIEW

**Comment by aschweigert** [comment]
throwing this to @kaeti to make sure we want to remove rounded corners in all of these places before merging

**Comment by kaeti** [comment]
This seems OK to me.

**Comment by rnagle** [comment]
Checked out the branch locally and glanced at a few sites. Seems fine to me, too.

I'm going to merge this to `develop` unless there's a pressing need for this on `master`.

**Comment by rnagle** [comment]
Merged to `develop`: 4f766b041877616fd759a1117ebe207039db8b4a

**Pull request closed without merging**
