### PR TITLE
refactor social media widgets

### PR DESCRIPTION
**Pull request by aschweigert**
still to do: 
- [x] add a filter to the largo follow widget to allow sites to add additional networks/links from a child theme
- [x] try to figure out why these brand colors/styles exist in the largo-follow.less and in single.less (seems wrong)
- [x] bleh, looks like some of those fb responsive styles are also needed, just not for this widget

### CODE REVIEW

**Comment by aschweigert** [comment]
nm, fb widget code was just way out of date

**Comment by aschweigert** [comment]
almost there, would still like to:
- [ ] update the twitter widget
- [ ] apply the same filter (largo_additional_networks) to the output of social icons in the header and footer

**Comment by aschweigert** [comment]
this will also eventually address #219

**Comment by aschweigert** [comment]
@jackbrighton you said as far as you could tell the twitter widget just needs the widget ID, right? none of the other parameters for the various widget types make a difference anymore?

**Comment by jackbrighton** [comment]
Yeah but that was a month ago or so while handling a related ticket and doing lot of other stuff. I'd like to quickly verify before we strip out code.

**Comment by aschweigert** [comment]
ok. no worries, just wanted to further test that hypothesis and make any necessary changes as we address this PR. found out, for example that the version of the fb like box we were using was no longer supported (hadn't been for over a year :(

**Comment by aschweigert** [comment]
@jackbrighton fyi re: the twitter widget, it's true that the text/url are not strictly necessary, but they are used as a fallback if the widget js doesn't load so it's probably worth keeping them

**Comment by jackbrighton** [comment]
Thanks, that's good to know!

**Comment by aschweigert** [comment]
Just a note that Twitter search widgets appear to be dead now. Probably a minor issue, but that's a thing.

**Comment by aschweigert** [comment]
This is good to go. We may at some point want to make it easier to add additional social networks to the regular theme options page but punting on that now. For a sample implementation of how to add a new social network to show in the follow widget and the row of icons in the header/footer, see: https://bitbucket.org/projectlargo/theme-gijn/src/cd95b21eb2bfc7ab2d338eaff1d5a9d1ff0149f4/inc/options.php?at=master&fileviewer=file-view-default

Note that you also need some CSS for whichever button you're adding if the icon you want is not included in our current fontello set.

**Pull request merged**
