### PR TITLE
Remove deprecated recommend widget from widget defaults.

### PR DESCRIPTION
**Pull request by willhaynes**
When the sidebar is empty, we (sometimes) include some default widgets. We should not be loading a deprecated widget in here.

### CODE REVIEW

**Comment by aschweigert** [comment]
If we do this we need to make sure the new widget is set to do the right thing (show the sidebar featured posts that would have appeared previously).

Even for new sites I'd question whether the recent posts widget should be included in the default stack of widgets...would we say that in 100% of cases sites would want to show X recent posts (with no filter applied) by default? I don't think so.

**Comment by rnagle** [comment]
So, with this change, the line up for the sidebar fallback would be:

- About this site
- Follow widget
- Support/donate widget (if donate link is specified in options)
- Recent posts
- Stories from INN members (if `INN_MEMBER` is true)

@aschweigert Could we just remove "Recent posts" and leave the others as they are? Or, should we scrap the entire fallback mechanism and just show "Go to the WP dashboard to add widgets to this sidebar" (or something along those lines)?

Apologies if I'm being daft, but I don't really understand why showing recent posts is a bad idea. Can you give an example where it would cause trouble?

**Comment by aschweigert** [comment]
I guess I just think this is maybe a bit heavy-handed as a default, probably makes more sense to just not load anything by default and show a notice pointing to the dashboard to add/configure widgets

**Comment by aschweigert** [comment]
has this been addressed already elsewhere?

**Comment by rnagle** [comment]
@aschweigert It doesn't look like this has been changed anywhere else.

I'll handle this, but before I do, I want to clarify -- we're talking about removing the existing fallback mechanism for the Main and Single sidebars, correct? That is, rather than show a default set of widgets, just say, "Hey, add some widgets to the '[Widget Area Name Here] Sidebar' via the WordPress dashboard."

**Comment by aschweigert** [comment]
I think for now leave the defaults, just remove the deprecated widget and account for that in the update script

**Comment by rnagle** [comment]
@aschweigert OK -- so the recommended widget is already being dealt with as a part of the update/upgrade process. Since the update process swaps in a featured posts widget, I went back and modified this PR to follow suit. If there are no objections, I'm going to merge and close this, finally.

**Comment by aschweigert** [comment]
works for me

**Pull request merged**
