### PR TITLE
Add standardized Mailchimp signup widget

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Adds `less/inc/widgets/widgets/largo-mailchimp-signup.less` with a style that makes labels within the widget inline, for compatibility with Mailchimp-provided checkbox markup. Largo by default makes labels `display: block;` which prevents placing checkboxes next to labels.
- Adds a style to largo's default to make `input[type=checkbox]` checkboxes *not* be 210px wide.
- Alphabetizes the array of widgets in `inc/widgets.php`
- Copies the Wordpress Text Widget to create the Largo Mailchimp Signup Widget, with the following fields:
    - the title
    - any prelude text, usually a call-to-action
    - the form URL
    - any additional html that needs to be inserted into the form, such as checkboxes or additional input fields
    - the anti-bot form field ID. (If this is left blank and the form is submitted, any text input on this field will not be passed to Mailchimp, effectively rendering the anti-bot form field useless.)
- A filter `largo_mailchimp_signup_output` that allows themes to edit the widget HTML.

With no title, additional HTML, or call-to-action text:

screen shot 2016-03-30 at 10 38 08 am

When the widget does not have a form URL configured:

screen shot 2016-03-30 at 10 38 58 am

Using default styles, a widget with added HTML:

screen shot 2016-03-29 at 9 36 02 pm

## Why

To provide a standard Mailchimp signup widget.

For [FE-175](http://jira.inn.org/browse/FE-175) and #1154.

Filed against master because presumably we'll want to deploy this with the corresponding child themes, and I'm not sure if those'll launch before or after 0.5.5. Filing against master means we don't have to wait for 0.5.5.

## Questions

- [ ] Where should user-facing docs go?
- [ ] How much documentation should be in the widget admin? Should the widget admin explain what the field IDs are, how to get them, how to find their values, what the values mean?

### CODE REVIEW

**Comment by benlk** [comment]
I have one concern about this widget, which is probably solvable through documentation: If there are multiple of this widget on the page, there will be multiple elements on the page with the same `id`, which is a no-no. The `id`s for the inputs cannot be changed, because those values are required for the receiving Mailchimp form page to work.

**Comment by aschweigert** [comment]
let's merge this to develop instead of master (similar to the search box in the header for MWEN/SEEN, we'll have some things we can remove when 0.5.5 ships, this will just be one of those additional things)

**Comment by aschweigert** [comment]
test, will this sync to github?

[--- Commented from Asana.com
#commenter Adam Schweigert
---[aa]

**Comment by benlk** [comment]
I'll refile this against develop, and solicit feedback on its documentation in that PR.

**Pull request closed without merging**
