### PR TITLE
Footer options megapull

### PR DESCRIPTION
**Pull request by benlk**
## To do

- [x] fix widget area not getting registered in 4col-asymm layout
- [x] check against all member child themes
    - SE Energy News
    - INVW
    - FE
    - NPQ
- [x] find member child themes that modify the boilerplate
- [x] check against other browsers, this only thoroughly tested in Chrome/ium
    - [x] IE9 in win7
    - [x] safari 8
    - [x] firefox 39
- [ ] check that the advice in `partials/footer-widget-area.php` is correct and functional

## Changes

- stubbed tests for `/inc/header-footer.php`
- tests for `inn_logo` and `largo_social_links`

#### Images

INN's normal, dark-on-light logo is now available at `img/inn_logo_blue_final.png`

If the INN logo images need to be replaced, some assumptions will need to be updated in `less/inc/footer.less`. These assumptions are documented there and in `img/README.md`

#### new footer options

`partials/footer-widget-area.php` has been broken into a number of partials. The `of_get_option('footer_layout')` layout is loaded with `get_template_part( 'partials/footer-widget', $layout);` if the template part is locatable with `locate_template`, otherwise it falls back to `3col-default`.

Documentation is included in `partials/footer-widget-area.php` for theme authors who want to add their own footer template, including instructions how to filter the options array.

- asymmetrical 4-column layout

screen shot 2015-08-04 at 8 38 32 pm

- centered one-column layout, which will mess up some widgets

screen shot 2015-08-04 at 8 39 49 pm

#### footer boilerplate changes

screen shot 2015-08-04 at 4 38 48 pm

screen shot 2015-08-04 at 4 39 11 pm

- footer collapses to centered single-column layout at 969px
- inn logo is now output by the new pluggable function `inn_logo`, so the default light-on-dark function can be swapped with the dark-on-light image. Documentation for this is in the images folder's new `README.md` and in `partials/footer-boilerplate.php`
- inn logo becomes smaller
- social media icons become smaller, appear vertically centered with the inn logo. **This may conflict/be overridden by child theme CSS**, as the `#footer` selector is now `ul#footer`.
- reword the footer credit
- remove the "Inn Member Since" credit
- boilerplate is now span6/span6, changed form span9/span3. **This may break child theme CSS**

## Why

- #761 and [FE-146](http://jira.inn.org/browse/FE-146)

### CODE REVIEW

**Comment by benlk** [comment]
## Affects on child themes:

These themes duplicate the footer widget area partial:

```
find . -iname "footer-widget-area.php" -print
```

`./ctmverticals/partials/footer-widget-area.php` - used on http://ctviewpoints.org/ and http://trendct.org/, establishes a 6-column span2 grid. No interference.
`./midwestenergynews/partials/footer-widget-area.php` - the 1col template, essentially. Has theme-specific CSS. Could be removed in future, but not essential to this update. 
`./npq/partials/footer-widget-area.php` - Standard 4col approach, but the fourth column is instead hosting the header subscribe image. Maybe we might want to move them to the 4col template with an image widget.
`./voiceofoc/partials/footer-widget-area.php` - duplicate of Largo's, but using deprecated [largo_cached_nav_menu](https://largo.readthedocs.org/en/latest/api/inc/deprecated.html). 

These themes duplicate the footer boilerplate partial:

```
find . -iname "footer-boilerplate.php" -print
```

- `./catalystchicago/partials/footer-boilerplate.php` - used on catalyst-chicago.org, replaces the boilerplate entirely. Not affected by this PR's changes.
-`./chicago-reporter/partials/footer-boilerplate.php` - used on chicagoreporter.com, replaces the boilerplate entirely. Not affected by this PR's changes.
-`./npq/partials/footer-boilerplate.php` - used on nonprofitquarterly.org, replaces boilerplate entirely with left logo, right social media, different layout and spacing of the copyrights. This PR's change affects only the coloration of the social media icons.
-`./se-energy-news/partials/footer-boilerplate.php` used on http://southeastenergynews.us/, replaces the boilerplate entirely. Not affected by this PR's changes.

**Comment by aschweigert** [comment]
Given that we now have literally a billion different options here, I'm pretty strongly in favor of making people pick one and remove all overriding partials and css from child themes (for the sites hosted with us anyway).

For the sites we designed/built we DEFINITELY should do this (and I don't think we really need to even run it by people, tbh, because it won't be a significant change). For the ones built by someone else we should let them know and give them a deadline to switch over before removing it from their child themes (unless they present a really compelling argument why it needs to remain the way it is now)

**Comment by benlk** [comment]
Catalyst Chicago and Chicago Reporter use this boilerplate partial:

screen shot 2015-08-05 at 3 22 41 pm

Southeast Energy News uses this boilerplate, which is our design: 

screen shot 2015-08-05 at 3 23 58 pm

I'm in favor of updating the NPQ, Voice of OC and MWEN widget areas, but the 6-column layout partial should probably stay with ctmverticals, because it isn't covered by Largo. And NPQ's boilerplate should be removed.

**Comment by aschweigert** [comment]
@benlk I think CT Mirror is probably flexible enough that if we make a recommendation it will be fine, particularly given that it's been broken on those two sites for weeks and they haven't even complained about it :)

**Comment by benlk** [comment]
My concern about SE Energy news is that they're adding "408 St. Peter Street Ste 220 St. Paul, MN 55102 info@fresh-energy.org 651-225-0878" to the boilerplate, and we don't have a way to add that back in if we remove their boilerplate partial.

We could get around this by adding a new action hook, `largo_after_copyright`, and then for their theme hook the address line to that.

- [x] remove NPQ partials
- [x] remove Voice of OC widget area partial
- [x] remove MWEN widget area partial
- [ ] SE Energy News?

## post-deploy

- [ ] update MWEN with 1col footer widget option
- [ ] update NPQ with 4col footer and a text widget: `<a href="<?php echo(of_get_option('subscribe_link')); ?>">" alt="Subscribe to Nonprofit Quarterly"></a>`
- [ ] ? remove SE Energy news social icons widget from footer-1,

**Comment by aschweigert** [comment]
We could standardize presentation of contact information in the footer, but otherwise I think using a hook is the logical way to go there (re: SE Energy)

**Comment by benlk** [comment]
Sounds good.

Should I create a ticket attached to 0.5.2 for umbrella post-deploy tasks, just so we have a central repository of those?

**Comment by aschweigert** [comment]
Sure, that makes sense to me

**Comment by benlk** [comment]
With the exception of testing [this advice](https://github.com/INN/Largo/pull/820/files#diff-1948e9990d34afc6ac4f33ab9bf4c683R5), this commit is ready to go. With the exception of the Chicago themes, affected child themes have been updated and added to #821.

**Comment by rnagle** [comment]
This is in great shape. Noticed one issue with the `4col-asymm` layout on smaller viewports:

image

Seems like the columns should stretch to fill the full width of the footer at that size. Otherwise, I think it's ready to merge.

If/when we're updating the docs it would be good to note you need `INN_MEMBER` constant defined and set to true in order for the INN logo to show up. I got tripped up on that during testing.

**Comment by aschweigert** [comment]
One other thing (can probably wait until this is merged): for the 4 col asymmetrical layout, using the default stack of widgets is a bad idea because the columns are too narrow. @kaeti can weigh in here, but I think the intent here is that they would only ever be used for nav menus. So we should probably figure out how to deal with that and at least TRY to keep people from making poor decisions.

**Comment by kaeti** [comment]
Yeah, for 4 column, nav menus and logos/smaller images (like an in house ad or something) work best.

**Comment by benlk** [comment]
This will now collapse .span* in the footer, instead of just collapsing the .widget-area divs.

**Comment by rnagle** [comment]
This looks ready to merge.

Created a ticket for @aschweigert's and @kaeti's comments on the 4 column asymmetrical layout: #829.

**Pull request merged**
