### PR TITLE
added template hook to category page, after div.primary-featured-post…

### PR DESCRIPTION
**Pull request by megabulk**
… and before div.secondary-featured-post

### CODE REVIEW

**Review by benlk — CHANGES_REQUESTED** [review]
@megabulk Please remove package-lock.json and resolve merge conflicts.

**Comment by benlk** [comment]
@joshdarby do you think this new `largo_category_after_primary_featured_post` filter should be in `category.php` or in `partials/archive-category-primary-feature.php`?

**Comment by benlk** [comment]
Before merge, this will need a notice of the new filters in `changelog.md`.

**Comment by benlk** [comment]
Also, @megabulk: starting with your work on Largo and the client site, we're going to try having labeled prerelease versions of Largo, as described at https://github.com/INN/largo/pull/1705. This doesn't affect your PR against Largo, but we will want to make sure that your umbrella repo has an updated Largo version number.

**Comment by megabulk** [comment]
Should I add it to .gitignore?

**Review by benlk — APPROVED** [review]

**Comment by joshdarby** [comment]
@benlk 

> @joshdarby do you think this new `largo_category_after_primary_featured_post` filter should be in `category.php` or in `partials/archive-category-primary-feature.php`?

@benlk Sorry, just saw this. I think it's fine in `category.php`. There _may_ be some cases where someone uses `partials/archive-category-primary-feature.php` but doesn't want to include that filter.

**Comment by benlk** [comment]
Then let's resolve conflicts and get this merged. https://gifs.benlk.com/will-ship.gif

We'll need to start the 0.6.4 section in https://github.com/INN/largo/blob/0.5-dev/changelog.md as part of this.

**Review by joshdarby — APPROVED** [review]

**Comment by joshdarby** [comment]
@benlk I've updated the changelog to reflect the updates in this PR + start the new 0.6.4 section.

**Comment by benlk** [comment]
LGTM. :shipit:

**Pull request merged**
