### PR TITLE
Update functions for #414 and enabling series and landing pages if they were in use before

### PR DESCRIPTION
**Pull request by benlk**
This commit provides:

- remove the old "Top Story" and duplicate "top-story-2" prominence terms on update
- enable series taxonomy if series were previously used
- enable the series taxonomy and series landing pages if series landing pages were previously used
- stubbed tests for the above

This is for:
- #414 for the duplicate prominence terms
- Adam mentioned the enabling of the series taxonomy, but I can't find a ticket for it.

### CODE REVIEW

**Comment by aschweigert** [comment]
Delete the "old" top story prominence term before the new one is created is probably not a great idea because then we'd lose track of which posts have that term assigned to them. It would be better to make the homepage templates check to see if this term already exists, and if so, not re-create it, I think. Is that possible?

**Comment by benlk** [comment]
It may be possible, but the constructor methods on the homepage classes aren't always run in a context where the `top-story` term exists, and I think we'd risk creating a lot of spare `top-story-n` classes.

I think it would less complicated (and more maintainable) to get the posts that are in the old `top-story` term and use [wp_set_post_terms](http://codex.wordpress.org/Function_Reference/wp_set_post_terms) to make sure the new top-story is added to them.

**Comment by aschweigert** [comment]
That would work too. As long as we make sure those relationships are preserved either solution would be fine, I think.

**Comment by benlk** [comment]
Different solution: Just turn the old "Top Story" into a new "Homepage Top Story" with [wp_update_term](http://codex.wordpress.org/Function_Reference/wp_update_term). Keeps all the posts, just changes practically everything about it:

- name "Homepage Top Story"
- slug becomes "top-story" (but this is actually unchanged)
- description is overwritten with the 0.4 description, 'If you are using a "Big story" homepage layout, add this label to a post to make it the top story on the homepage'
- gets rid of the parent relationship to "Homepage Featured"

**Pull request merged**
