### PR TITLE
Post social icon styles updates

### LINKED ISSUE #950: Should article-bottom widgets have padding similar to sidebar widgets?
screen shot 2015-10-28 at 3 30 47 pm

The social icons in this screenshot inherit the following styles from the general `.widget` selector:

```css
.widget {
    padding: 0 24px;
    margin-bottom: 36px;
}
```

In this screenshot, the widget wraps because there is additional padding in the widget bottom that is not in the widget top.

Should we limit this padding-left and padding-right to the sidebar widgets?

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Removes `.left` and `.right` grouping of social icons
- Removes the padding around general `.widget` and puts it on `#sidebar .widget`.
- Replaces `.icon-email` class on containing `span.email` with an `i.icon-email` inside the span, for consistency
- Removes the responsive style that hid the print button on mobile.
- Adds `.hidden-phone` to the text labels.
- Adds `.largo-follow` to the post social icons at the top of the article page, so that that grabs styles from the Largo Follow widget for coloration of buttons. (This could be done the other way around as well: copy the Largo Follow styles into the post social section of `single.less` and then add their class to the Largo Follow widget.)
- Does not affect the Largo sticky footer.

Width of 420 px, approximately phone-like:

screen shot 2015-10-28 at 4 27 39 pm

Width of 769 px, the smallest at which the labels will show.

screen shot 2015-10-28 at 5 36 29 pm

The padding on the left of these icons is because of the problem described in #950.

## Why

For [WE-18](http://jira.inn.org/browse/WE-18), and Women's eNews and RNS.

For #950, which had the problem where widgets in the article-bottom position were not as wide as the column:

screen shot 2015-10-28 at 3 30 47 pm

## Questions

- [ ] should I move the coloration styles out of `.largo-follow`?
- [x] should this fix #950?

### CODE REVIEW

**Comment by aschweigert** [comment]
What's with the weird left margin when it's at the bottom of the post?

**Comment by benlk** [comment]
https://github.com/INN/Largo/issues/950 is what's up. Should I tackle that here?

**Comment by aschweigert** [comment]
yes.

**Comment by benlk** [comment]
Updated with a fix for #950 and new screenshots.

**Comment by benlk** [comment]
Moving coloration styles out of .largo-follow isn't essential.

Looks good in the Android 4.2.2 browser:

screenshot_2015-11-03-12-18-40

screenshot_2015-11-03-12-19-00

**Comment by benlk** [comment]
Now with proper `:hover` colors.

**Comment by rnagle** [comment]
Going to merge this to `develop`.

We'll still need a thorough check of member themes before we're able to deploy this.

**Comment by aschweigert** [comment]
@benlk the email button is not working for me, is that a known issue?

**Comment by benlk** [comment]
Unless it's #799, it's not a known issue.

**Pull request merged**
