### PR TITLE
Styles for the Analytic Bridge Plugin's Popular Posts Widget in Largo

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Creates `less/inc/widgets/analytic-bridge-popular-posts.less` for styles for this widget, and creates a new section in `less/inc/widgets.less` for INN-supported widgets not in Largo.
- Styles for the ABP Popular Posts widget in the sidebar:
    - widgets are separated by a 1px light grey line
    - images have the same spacing between the image and the headline as between the headline and the border
- Styles for `ol` ordered list version of this widget in the sidebar:
    - Hide the normal list counter, which is pretty much impossible to style and which under CSS 2.1 [has undefined, user-agent-dependent behavior](http://www.w3.org/TR/CSS2/generate.html#propdef-list-style-type)
    - `li::before` with a custom counter that inserts a large number before the icon, positioned according to the RNS wireframes. Help here came from [this Red Team Design article](http://red-team-design.com/css3-ordered-list-styles/), which talks about CSS3, but this is all supported in CSS2.
    - the counter uses Largo's sans font by default.
    - 10px padding between the number's box and the image or headline
    - Headlines have a `min-height` the height of the number, to preserve spacing.

## Screenshots

The RNS wireframe:

screen shot 2015-12-07 at 11 36 14 am

Default Largo `ol` styles:

screen shot 2015-12-07 at 12 39 13 pm

Numbers greater than 9 are supported:

screen shot 2015-12-07 at 12 39 30 pm

An `ul` without the numbers or thumbnails:

screen shot 2015-12-07 at 12 40 01 pm

## To do:

- [x] test in IE8
- [x] test in Firefox
- [x] test in Safari
- [x] ~~remove the styles commits from #1003, to prevent conflicts~~ #1003 will probably be closed.

## Notes about styling this for child themes:

- Thinner fonts may require adjusting the width of `li::before` and the margin-left on the `li`.
- The selector for the `::before` counter is going to be ``#sidebar .widget_analytic-bridge-popular-posts ol li::before``.

### CODE REVIEW

**Comment by benlk** [comment]
@kaeti when you get a chance, can you see whether this looks okay on narrower desktop browsers?

**Comment by kaeti** [comment]
Sure, is it up somewhere where I can test it?

**Comment by benlk** [comment]
Not yet. If you've got a few minutes tomorrow to pair on it, I can show you and we can go over the styles.

**Comment by kaeti** [comment]
sounds good

**Comment by benlk** [comment]
For #971 and WE-20 and CS-22

**Pull request merged**
