### PR TITLE
sticky nav conditional for aspen

### PR DESCRIPTION
**Pull request by dryanmedia**
add conditional to displaying site header only on home page

### CODE REVIEW

**Comment by aschweigert** [comment]
hm. this conditional probably belongs in the largo_header function because that's where the other logic is re: the header images on internal pages. Doesn't HAVE to be that way and maybe it makes more sense to put that conditional somewhere else, but it should definitely be in the same place either way, not in both places.

**Comment by aschweigert** [comment]
see: https://github.com/INN/Largo/blob/master/inc/header-footer.php#L8

**Comment by dryanmedia** [comment]
@aschweigert how's this lookin'?

**Comment by aschweigert** [comment]
line 16 (https://github.com/INN/Largo/blob/870-text-only-header/inc/header-footer.php#L16) and line 30 (https://github.com/INN/Largo/blob/870-text-only-header/inc/header-footer.php#L30) should probably be the same conditional for consistency. Any thoughts re: how we might want to refactor/streamline this function @rnagle?

**Comment by rnagle** [comment]
The most glaring issue (that @aschweigert identifies above) is that anytime you check `of_get_option('show_sticky_nav')`, you'll also want to check `SHOW_STICKY_NAV` to determine whether or not the setting is overridden by the constant. So, we might consider wrapping that up in a `largo_sticky_nav_enabled()` function.

**Comment by dryanmedia** [comment]
@rnagle how does that wrapper look to you?

**Comment by aschweigert** [comment]
@dryanmedia please resubmit this PR against the develop branch

**Pull request closed without merging**
