### PR TITLE
Fix Largo_Related::popularity_sort sort

### LINKED ISSUE #1868: Largo_Related::popularity_sort sorts in wrong order
## The problem

Copying from https://github.com/INN/umbrella-sfpublicpress/issues/111

> A quick review of the terms assigned to this post:
> 
> - tag "police brutality" has one post, which is the initial post
> - tag "police reform" has one post, which is the initial post
> - tag "protests" has three posts, which the initial post and two of the three related posts
> - tag "protest" has 8 posts, of which 4254 is the post in that tag previous to this post
> - category "Social Justice" has 124 posts
> 
> When `Largo_Related` is generating posts from the categories and tags that are assigned to the initial post, it grabs all category and tag terms that apply to the current post, and then sorts them by popularity before looping through them to find posts to add to the "related" list.
> 
> https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L694-L696
> 
> The function `popularity_sort` is a method of `Largo_Related`, and if its behavior here is to be believed, it's sorting the less-used terms before the more-used terms.
> 
> https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L550-L560
> 
> As a result, no posts are grabbed from "police brutality" or "police reform", the two posts from "protests" are added, then with one more post to grab Largo_Related grabs the next-earlier post from "protest", and then because it has three posts to equal the requested count of three, it's done. It never reads the category.
> 
> But as far as I can tell, based on [usort](https://www.php.net/manual/en/function.usort.php) and [ternary operator](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary) docs, this code is written to perform the opposite way of how it's behaving.
> 
> ```php
> 		return ( $a->count < $b->count ) ? -1 : 1;
> ```

> So this is what's actually happening:
> 
> Given tags and counts
> 
> - c -> 4
> - a -> 3
> - f -> 2
> - e -> 1
> 
> This usort sorting function will return `e,f,a,c` instead of `c,a,f,e`, because it orders _from least to greatest_.
> 
> So _of course_ it's picking from the lower-count terms.

----

## Solution

- [ ] swap `-1` and `1` here:

https://github.com/INN/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/related-content.php#L559

### PR DESCRIPTION
**Pull request by pedroxido**
## Changes

This pull request makes the following changes:

- 

Updated `inc/related-content::popularity_sort`, line 559, to invert the sort order

## Why
Sort was beign performed in the incorrect order as mentioned in issue #1868
For #1868 

## Testing/Questions
N/A

- [ X ] Is this PR targeting the correct branch in this repository?
- [ ] 

## Additional information

INN Member/Labs Client requesting: (if applicable)

- [ X ] Contributor has read INN's [GitHub code of conduct](https://github.com/INN/.github/blob/master/CODE_OF_CONDUCT.md)
- [ X ] Contributor would like to be mentioned in the release notes as: pedroxido
- [ X ] Contributor agrees to the license terms of this repository.

### CODE REVIEW

**Comment by pedroxido** [comment]
@benlk I picked this issue as part of the Hacktoberfest 2020, could you please review it?

**Comment by joshdarby** [comment]
@pedroxido Just a heads up that INN is no longer maintaining Largo.

**Comment by pedroxido** [comment]
> @pedroxido Just a heads up that INN is no longer maintaining Largo.

@joshdarby does that mean that the issue won't be reviewed anytime soon? or that I just tagged the incorrect reviewer?

**Comment by joshdarby** [comment]
> @joshdarby does that mean that the issue won't be reviewed anytime soon?

@pedroxido Correct. I'm not sure if @benlk will be available to review it any time soon.

**Comment by benlk** [comment]
@pedroxido Can you describe the tests you used to make sure this works as intended? That may help any future maintainer decide whether to merge this PR.

**Review by joshdarby — APPROVED** [review]

**Pull request merged**
