### PR TITLE
switch from identity to equality

### PR DESCRIPTION
**Pull request by dryanmedia**
The identity operator doesn't work in this situation.

This pull addresses the issue with load more posts not grabbing the correct partial on New Mexico In-Depth.

Files changed:
inc/ajax-functions.php

### CODE REVIEW

**Comment by benlk** [comment]
Why does this need to move from identity to equality? Is the stored value truthy but not `True` or `1`?

PHP Parse error:  syntax error, unexpected T_STRING in /tmp/wordpress/src/wp-content/themes/Largo/inc/ajax-functions.php on line 49

**Comment by dryanmedia** [comment]
@benlk this was originally to fix the loading of the correct partial for series landing pages. it wasn't loading. can't say I troubleshooted this farther than I switched from identity to equality while debugging and then the correct partial loaded and nothing else broke. This is for the Fathom special template we did for them.

https://github.com/INN/Largo/commit/f012c356012ad5d5d5aedb147049ae2f8ee13eed#diff-398a118e99c24ab047a94c1a898033e9R110

**Comment by benlk** [comment]
iiirc, we store that option as string `'1'`, which is what probably broke the identity. But the value should probably be always truthy unless it's disabled, so I don't think this is a problem.

**Comment by benlk** [comment]
Tests pass now, after swapping '' for "".

:+1:

**Comment by rnagle** [comment]
Took a look at this with David and changed a few things. Couple notes:

- We need to use `$_POST['is_series_landing'] == 'true'` here since the `is_series_landing` that gets sent over the wire from the front end and doesn't keep its boolean data type.
- We added a `largo_lmp_template_partial` filter to allow for the utmost flexibility in deciding which template to load in particular contexts and locations.

**Comment by rnagle** [comment]
Merged this to `develop` with b9b301230065358e3f8507571a9861de55b9acee.

**Pull request closed without merging**
