### PR TITLE
Use before-queries in addition to after-queries to find related posts in series and terms

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This brings back some of the pre #676 functionality of Largo_Related.

The current behavior of Largo_Related's `get_series_posts()` and `get_term_posts()` methods is to look for posts published after the current post, using a `date_query` argument. This doesn't work if the current post is the most-recently-published post in the post's taxonomies.

Under this PR, those two methods will first run with the `after` argument in `date_query`. Then, if not enough posts are returned, they will rerun the query with `before`, before progressing to the next method in the Largo_Related query stack.

This is a slight performance hit, in that the number of queries can increase, but it brings back the before-and-after functionality without loading the entire taxonomy term's worth of posts into memory. (See #680.)

## Why

For #782:

> We should definitely not make the assumption that only a newer post in the category/tag/term would be a valid match before it falls through to just most recent. I'd say at least looking for one previous post in the category/tag/term would be the desired behavior.

### CODE REVIEW

**Comment by rnagle** [comment]
This looks good to me. We really should write some tests for `Largo_Related` one of these days.

I think I'm going to merge this to `develop` unless it is meant to serve as a hotfix that must go out today.

**Comment by benlk** [comment]
It's not a hotfix, but there are some sites in prod that were complaining about only recent posts showing up on the most-recent-post.

**Comment by rnagle** [comment]
OK -- merging to `develop` as I intend to merge that to `master` and deploy that today.

**Comment by benlk** [comment]
:+1:

**Comment by rnagle** [comment]
Merged: da8c48bf18e4dc90199a1f6d12e0e31136ba3513

**Pull request closed without merging**
