### PR TITLE
Fix for tags not aligining properly in Largo Tag List widget

### PR DESCRIPTION
**Pull request by benlk**
## Changes:

Before:

screen shot 2015-08-14 at 12 21 32 pm

After:

screen shot 2015-08-14 at 12 18 44 pm

screen shot 2015-08-14 at 12 18 27 pm

## Why

For [YT-57](http://jira.inn.org/browse/YT-57). Tags in the Largo Tag List widget have, in the past, been styled inline, aligned left. They are not currently.

### CODE REVIEW

**Comment by aschweigert** [comment]
This seems fine, to me. @kaeti do you have any thoughts on this? It's no longer on story pages by default but once in a while a site still wants it so we should just make sure the styling looks decent, etc.

**Comment by kaeti** [comment]
I think we could make the styles for this even simpler. Ditching the icons, using commas or pipes to separate, and putting tags in line with the "Filed Under" label, making the default font size smaller. Attaching a couple of examples for inspiration. 

screen shot 2015-08-14 at 11 46 07 am

screen shot 2015-08-14 at 11 48 25 am

**Comment by benlk** [comment]
Minor note: The widget displays categories as well as tags.

**Comment by kaeti** [comment]
screen shot 2015-09-02 at 9 49 19 am

An option. 

- For the hover state, use an underline and 10% lighter gray (or something like that — would be good to hook into default hover styles for Largo/widgets so it can be easily changed)
- Used Helvetica Neue Light for the tags themselves, and bold for the word "tags"
- Two spaces on either side of the pipes
- Stripping this of color and personality so people can customize with their site styles
- the font size can be small (smaller than the body copy). Think footnotes.

**Comment by benlk** [comment]
The changes here are in a radically different direction from what this PR makes, so I'm going to make these changes a PR against the "Break everything apart" branch here: https://github.com/INN/Largo/pull/882

**Comment by benlk** [comment]
The new PR is https://github.com/INN/Largo/pull/887

**Pull request closed without merging**
