### PR TITLE
Update .travis.yml with wordpress 4.4, 4.3. Remove Wordpress 3.9 and 4.0

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Adds 4.4 and 4.3 to `.travis.yml`
- Removes the outdated 3.9 and 4.0
- Updates 4.1 and 4.2 to their latest bugfix versions.

This PR does not fix any tests. it only updates .travis.yml.

## Why

Because #1020, and there might be tests failing as a result of changes in versions of WordPress.

### CODE REVIEW

**Comment by benlk** [comment]
- [x] an error
```
1) PostTemplatesTestFunctions::test_insert_image_no_thumb
Indirect modification of overloaded property PostTemplatesTestFunctions::$ids has no effect
/tmp/wordpress/src/wp-content/themes/Largo/tests/inc/test-post-templates.php:77
/tmp/wordpress/src/wp-content/themes/Largo/tests/inc/test-post-templates.php:20
```

**Comment by benlk** [comment]
There are some tests here that are only failing under PHP 5.5, and some only under PHP 5.3.29, and some that only fail under WordPress 4.4.2 (current stable).

PHP 5.3 is end-of-life, but we keep it around because the deploy-tools virtual machines use it (and use a version of Ubuntu 2 years old, without backports), and specifically use PHP 5.3.10. Without special work, the vagrant boxes will never receive PHP 5.3.29.

I'm not sure that we need to keep PHP 5.3.

WP Engine uses PHP 5.5: http://phpinfo.wpengine.com/

They're our primary target.

**Comment by aschweigert** [comment]
do we know what tests are failing?

**Comment by benlk** [comment]
- array to string conversion inside a related content function that gets the post before and after a given post: https://github.com/INN/Largo/blob/master/tests/inc/test-related-content.php#L441 (one errored test in PHP 5.5)
- this line in the update functions' run of the Custom LESS updater: https://github.com/INN/Largo/blob/1020-update-travis-latest-wordpress/inc/update.php#L510 (`Non-static method Largo::is_less_enabled() should not be called statically`) (causes two errored tests in PHP 5.5)
- Something changed in WordPress' taxonomy code in 4.4.x that makes the prominence term description updater fail in PHP 5.3.29 and 5.5.x: https://github.com/INN/Largo/blob/1020-update-travis-latest-wordpress/tests/inc/test-update.php#L333

**Pull request merged**
