### PR TITLE
Optional post types

### PR DESCRIPTION
**Pull request by benlk**
This depends on/extends #328, and cherrypicks the post-type-specific commits from #312. It is half of the solution to #282.

Unless the option box is checked in Theme Settings > Advanced:

- The "Post Types" menu item is removed from the sidebar in the dashboard
- The "Post Types" metabox is removed from the post editor
- The "Post Types" column is removed from the table of posts and details

### CODE REVIEW

**Comment by rnagle** [comment]
Should the post types (and series) taxonomy be opt out instead of opt in?

What happens when we deploy this for sites that are using the develop branch of Largo and are already using post types or series?

**Comment by aschweigert** [comment]
I think opt-in makes most sense. And for the sites we've already deployed, I think only Wisconsin is using both, the others I believe use the series one but not the post types one so we might just need to handle it on a case by case basis rather than try to write an update script to account for it.

**Comment by benlk** [comment]
If they're already using it, this doesn't remove any actual functionality. It just hides the UI elements.

**Comment by aschweigert** [comment]
Yeah, so we'd basically just need to go back in and turn it on for those sites.

**Pull request merged**
