### PR TITLE
Additions/edits to sidebarwidgets.rst

### PR DESCRIPTION
**Pull request by jackbrighton**
# Changes: 

Updates Largo Docs:

- Updates Largo Recent Posts after changes to the Largo Recent Posts widget
- Adds Saved Links Widget section
- Adds section on Default WordPress Widgets Disabled

# Why?

These updates and additions are needed per https://github.com/INN/Largo/issues/847

# Still to do with the Largo Docs:

- The taxonomy list widget will need updated docs when https://github.com/INN/Largo/pull/1171 is merged
- Will need to add DFP widget
- Will need to add Analytics Bridge widget
- Probably still want to break the widget section into separate pages

### CODE REVIEW

**Comment by aschweigert** [comment]
Re: widgets added by plugins, we probably don't want to include these directly in the docs for largo itself because it would be confusing to people not to see those if they don't have the plugins installed and activated. We might want to just note that plugins sometimes add additional widgets and link to the relevant ones we build/support in their respective repos where applicable.

**Comment by aschweigert** [comment]
The rest of this looks fine, but let's remove the link roundups related stuff before merging

**Comment by jackbrighton** [comment]
Got it. Among the plugins we note here, do we want to include:

- Pym Shortcode plugin
- Term Debt Consolidator
- Super Cool Ad Inserter
- DoubleClick-for-WordPress
- Analytic Bridge

Some of these need better docs also.

**Comment by aschweigert** [comment]
most of those don't add any widgets, it would just be dfp, analytic bridge and link roundups

**Comment by jackbrighton** [comment]
Updated to mention just DFP, Link roundups, and analytic bridge plugins.

**Comment by benlk** [comment]
Do we want to do this for 0.5.5, or have these docs been moved to largo.inn.org?

**Comment by aschweigert** [comment]
probably move to 0.5.5, just make sure everything here has, in fact, been moved over there

**Pull request closed without merging**
