### PR TITLE
Adding conditionals functions.php

### PR DESCRIPTION
**Pull request by willhaynes**
This is more of a pull suggestion rather than a request.

Landing page functions are only `include()` if they're enabled, but a conditional check to `is_series_landing()` should probably be allowed at any point.

This change would add a conditionals.php file to organize other conditional checks. There's several that could be useful one line functions (think is there a byline override?, is a plugins installed?, &c).

Landing page functions are only `include()` if they're enabled, but a conditional check to `is_series_landing()` should probably be allowed at any point.

This change would add a conditionals.php file to organize other conditional checks. There's several that could be useful one line functions (think is there a byline override?, is a plugins installed?, &c).

### CODE REVIEW

**Comment by aschweigert** [comment]
this makes sense to me, probably cleaner than having these spread out in various other files

**Comment by willhaynes** [comment]
Second question:
Do we prefix these with `largo_`?

_@rnagle can we rerun Travis? I think he just got hung up on something._

**Comment by aschweigert** [comment]
I think I'm pro-prefixing everything. @rnagle?

**Comment by rnagle** [comment]
- Yes, I am pro-prefxing Largo functions with `largo_`
- Are we OK with moving this function out of the taxonomy landing page plugin that it (presumably) came bundled with and calling it part of Largo? Could this move present maintenance issues down the road?
- There are two `conditionals.php` files, one of which is unused and should be removed.

**Comment by aschweigert** [comment]
always, always prefix the functions. let's make sure that's added to our code style guide if it isn't in there already.

**Comment by willhaynes** [comment]
@rnagle I wrote this function in the first place and bundled it naively with the plugin itself. It's our function though.

No idea where that second conditionals.php file came from. Let's get that out of there.

**Comment by rnagle** [comment]
Awesome. Would you mind adding the `largo_` prefix and update any occurrences of `is_series_landing()`?

**Pull request merged**
