### PR TITLE
Adds filter for the Analytic Bridge Popular Post widget options.

### PR DESCRIPTION
**Pull request by benlk**
## Changes

For #971, this adds a filter function that runs on the Analytic Bridge Popular Posts widget that coerces the widget in the Article Bottom area to display only three posts, and to display thumbnails.

The choice of ol or ul is not affected, and the widget options are not saved here.

-----

Not in Largo: [this commit in INN/analytic-bridge](https://github.com/INN/analytic-bridge/commit/b1641870c294a5b3c5c906cc1ce1681ef756686f) also adds a message to the widget admin, which only appears when this filter function exists, that warns users of the effects of the filter.

## Why

For WE-20 and CS-22, and https://github.com/INN/analytic-bridge/issues/13.

This will enable the three-column layout needed for Women's eNews and Cornell Sun in the article bottom area.

### CODE REVIEW

**Comment by benlk** [comment]
Notes from discussion with Ryan:

- These options should be the defaults for the article-bottom area, but coercing isn't the right way to do this. Users should be able to override the defaults.
- Is there a way to set the optinos here when you put it into the admin? the widget's form() method is only passed $instance, not the sidebar's $args which contains the widget's location: https://github.com/INN/Largo/pull/1003/files and https://github.com/INN/analytic-bridge/commit/b1641870c294a5b3c5c906cc1ce1681ef756686f

**Comment by benlk** [comment]
Now with styles for the three-column article-bottom default, fulfilling the CSS portion of #971.

**Comment by benlk** [comment]
Should the article-bottom widget styles be a separate PR from the three-column forcer?

Question that might let us do the note better, without forcing: Does the form() function have access to the $args variable through something in the widget class's methods or properties?

**Comment by benlk** [comment]
Cherry-picking af93592 and creating a new branch just for the styles.

**Comment by rnagle** [comment]
@benlk re: our discussion last week about modifying the defaults via javascript when the widget is placed in the article bottom widget area -- @kaeti suggests it might be fine to change the defaults to just be what we want for the article bottom area. This would keep us from having to write a bunch of code. Not sure if this fits the requirements, generally speaking. Any thoughts on this?

**Comment by benlk** [comment]
So the defaults would then be three posts, thumbnails, and ordered list? That's okay with me.

The list decorations don't show up in the article-bottom widget if it's an ol or a ul, so we can leave the ol setting for posts in the sidebar.

:+1:

**Comment by benlk** [comment]
In that case, this PR can be closed and the branch deleted, because the styles are now in #1005.

**Comment by rnagle** [comment]
@benlk OK -- is the plan to set the defaults properly in the new styles branch as well?

**Comment by benlk** [comment]
Yep, it can do that.

**Comment by benlk** [comment]
Scratch that, the defaults need to be set in the plugin; I'll change them there.

**Comment by benlk** [comment]
They are now set in the master of the plugin.

**Pull request closed without merging**
