### PR TITLE
Adding HTML comment in markup when registering sidebars

### PR DESCRIPTION
**Pull request by seanchayes**
#1482 
I've added the id to the register_sidebar to be output as an html comment in part of the ```before_widget``` markup.

The other option would be to do the same but as a class.

@benlk 
@INN/tech-team

### CODE REVIEW

**Comment by benlk** [comment]
This is an interesting way of doing it; thank you! Can you provide some output code from this on pages, perhaps a diff of a homepage or category page with sidebars, diffing current `0.5-dev` with this PR? If not, we'll get around to doing that diff ourselves later.

**Comment by seanchayes** [comment]
I've captured these screenshots of the the markup when using this branch of code for the home page, a category/archive page and an article page.

I have added diff files too after each one.

**Article page**
largo-article-sidebar-naming
[article-diff.txt](https://github.com/INN/largo/files/2858533/article-diff.txt)


**Category / archive page**
largo-archive-sidebar-naming
[archive-diff.txt](https://github.com/INN/largo/files/2858532/archive-diff.txt)


**Homepage**
largo-homepage-sidebar-naming

[homepage-diff.txt](https://github.com/INN/largo/files/2858530/homepage-diff.txt)

As an option, if desired, I could add a closing html comment in the sidebar code too. So we have ```<!-- Sidebar name -->``` in the ```before_widget```. I could add ```<!-- / Sidebar name -->``` to the ```after_widget```

Regardless let me know if you have any questions.

**Comment by benlk** [comment]
This is approved for merge; @seanchayes how would you like to be credited in the changelog, release notes, and readme lists of contributors?

**Comment by seanchayes** [comment]
Yes - thank you.

**Comment by benlk** [comment]
What name should we call you by in those places?

**Comment by seanchayes** [comment]
Just like most of the other:

seanchayes with link to Github profile https://github.com/seanchayes/
 please.

Thank you

**Pull request merged**
