### PR TITLE
Update TGMPA class

### PR DESCRIPTION
**Pull request by GaryJones**
2.3.6 to 2.5.0

### CODE REVIEW

**Comment by jrfnl** [comment]
You may also want to adjust the config in https://github.com/INN/Largo/blob/develop/inc/plugin-init.php as some settings were deprecated in v2.4.0 and new ones introduced in v2.5.0.

For more information on the current settings: http://tgmpluginactivation.com/configuration/

Most notable changes:
* `'parent_menu_slug'` and `'parent_url_slug'` were removed in 2.4.0. Similar functionality was re-introduced in 2.5.0 with the `'parent_slug'` and `'capability'` config options.
* A number of new strings were introduced. If you have translations available, you may want to consider giving back as TGMPA intends to start providing native translations.

**Comment by rnagle** [comment]
Thanks for the update!

**Comment by jrfnl** [comment]
@rnagle FYI - in the mean time TGMPA 2.5.2 has come out, upgrading to that version is highly recommended.

**Comment by benlk** [comment]
Does TGMPA 2.5.2 bring any advantages over 2.5.0 than the hotfixes? https://github.com/TGMPA/TGM-Plugin-Activation/releases

**Comment by jrfnl** [comment]
No, but the hotfixes solve some serious issues people where experiencing when different versions of TGMPA where loaded by - for instance -a plugin and a theme and are therefore important to apply.

**Pull request merged**
