### PR TITLE
Break up largo_byline()

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Guts `largo_byline` and creates a new action for it, `largo_byline_action`, which is passed an array of arguments for the following default hooked functions:
    - `largo_byline_component_authors` - This is further split into the following functions, which are run depending on whether or not the Co-Authors Plus plugin is enabled and whether or not the post has a custom byline. The output of these functions is then wrapped in the Largo `span.by-author` and associated HTML:
        - `largo_byline_coauthors` is a wrapper around the action `largo_byline_coauthor_each`, which fires for each coauthor on a post, and has the following default hooked functions:
            - `largo_byline_avatar` - dual-use function that gives avatar for all author types. If the author doesn't have an avatar uploaded, it tries to use the Gravatar, and otherwise is styled to not appear. The styles added for the avatar limit it to the normal line-height of the byline.
            - `largo_byline_coauthor_each_component_author` - outputs the coauthor, linked to their posts, and their organization if it's set
            - `largo_byline_coauthor_each_component_job_title` - if the Largo option is set, outputs the job title for each coauthor
            - `largo_byline_coauthor_each_component_twitter` - if the author has a Twitter handle, output that
        - `largo_byline_normal_or_custom` is a wrapper around the action `largo_byline_normal_or_custom`, which is used for stuff if the author is a normal WordPress user or if there's a Largo custom author set. This collusion is because many existing Largo functions were built to handle this case.
            - `largo_byline_avatar` - as above
            - `largo_byline_normal_or_custom_component_author_link` - a wrapper for `largo_author_link`
            - `largo_byline_normal_or_custom_component_author_job_title` - output the job title if there's a job title and if job titles are set to display and if there's not a custom author
            - `largo_byline_normal_or_custom_component_author_twitter` - output the author user's twitter handle if there's one and if there's not a custom author
    - `largo_byline_component_sep` - outputs a separator `span.sep`.
    - `largo_byline_component_publish_datetime` - outputs the `largo_time` publish time.
    - `largo_byline_component_edit_link` - the admin-only edit link is now handled by an action instead of the `largo_byline` function.

- Creates new files, and moves some functions out of `inc/post-tags.php` into them:
    - `inc/pagination.php`
        - largo_entry_content
        - largo_custom_wp_link_pages
        - largo_content_nav
    - `inc/post-social.php`
        - largo_post_social_links
        - largo_floating_social_buttons
        - largo_floating_social_button_width_json
        - largo_fooating_social_button_js
- Moves these functions out of `inc/post-tags.php`:
    - largo_post_metadata into `inc/header-footer.php`
    - largo_hero_class into `inc/featured_media.php`
    - largo_hero_with_caption into `inc/deprecated.php`

## Why

Because #1126 and it was about time to make this more easily modified.

## To do

- [x] stub tests
- [ ] RST docs for these hooks and their parameters

### CODE REVIEW

**Comment by aschweigert** [comment]
@benlk Sorry to do this, but can you split this PR up so the moving functions around stuff is in a separate PR and the byline stuff is in a PR by itself so it's a little easier to review? (I would also probably pull it out as a separate byline.php file instead of stuffing all of that into post-tags.php) 

My general feeling here is that this is a pretty overcomplicated and we're going to need to simplify it somewhat. The function names are also insanely long and that's just not going to work. We probably need a largo_byline class to wrap all of this stuff and then all of these other functions would be contained therein to make the structure a little clearer and the names a little more sane.

On a more minor note, try also to make sure you're following WP code standards re: whitespace, etc. so this is easier to read and takes a little less time for me to review :)

**Comment by benlk** [comment]
- [ ] split PR into byline PR and move-functions-around PR
- [ ] make the byline function names simpler
    - [ ] `largo_byline` becomes a wrapper around the `Largo_Byline
- [ ] scrap actions? Make it easier to read, in any case. If actions are scrapped, just place the functions in the spot where the action was.
- [ ] continue improving docs

**Comment by benlk** [comment]
Our main goal is to improve the byline function, but do we have a secondary goal of making the byline easier to modify?

**Comment by aschweigert** [comment]
a byline is:

- one or more authors
- date
- edit link

Easy stuff first:

- The date could be slightly more complicated by adding an updated date in addition to the published date. This would possibly replace the published date OR it might be appended after it.
- The edit date is only shown to logged in users who have sufficient privileges to edit the current post/page

Harder stuff:

Authors.

- Having three ways to add an author is very confusing for users and we should simplify this wherever we can. 
- To that end, we should lose the largo custom byline stuff and just use co-authors plus IF a site needs either guest authors OR more than one author for any given story. Creating a guest author is not that hard/problematic and it has many advantages over storing this as "dumb" text in post meta.
- The default format of an author should be a smart default and we should hold the line re: the design. It includes (for now): avatar (optional), name/link to author archive page (required), twitter (optional).

We'll need some backwards compatibility for older sites using custom bylines or a migration function but this SHOULD NOT be the default and we should work toward deprecating this.

**Comment by aschweigert** [comment]
I am far less concerned with being able to modify this from child themes as long as the defaults are good and we have the above options covered.

**Comment by benlk** [comment]
Deprecating the Largo custom bylines seems like a separate issue and PR from this PR, the original goal of which was to make the bylines easier to modify.

In any given install of Largo, there are only two ways to set an author: custom bylines and one of ( the default WordPress author way or the Co-Authors Plus author way ).

A migration function for custom bylines -> Co-Authors is going to require a lot of separate work and testing. I'm not sure if it should be in the Largo's update function or in [INN/wp-scripts](https://github.com/INN/wp-scripts)

This is what needs to be done to this PR, and to the functions, then:

- [ ] create issue for deprecating custom bylines in next major version of Largo
- [ ] split this PR into a byline PR and a move-functions-around PR
- [ ] make the byline function names simpler. `largo_byline` becomes a wrapper around the `Largo_Byline` class, containing all these functions.
- [ ] scrap actions within the coauthor/not byline functions. Just place the component functions in the spot where the action was, in the correct order. (Output buffering can stay, it makes it easier to run the `largo_byline` filter). If child themes want to modify the byline, they can plug the `largo_byline` function or use the `largo_byline` filter.

The custom-byline-deprecation issue/PR would build upon this, removing all the conditional checks regarding custom bylines.

**Comment by benlk** [comment]
Pseudocode, as requested

```php 
// this function remains its usual pluggable self
largo_byline( $args ) {
	// find whatever's needed: post ID, etc
	new Largo_Byline( $args );
}

Largo_Byline( $args ) {
	__construct( $args ) {
		// do the setup, whatever's necessary

		// the byline portion, which should be its own function
		if it's a custom byline or Coauthors isn't installed {
			avatar();
			author_link();
			job_title();
			twitter();
		} else Coauthors is installed {
			foreach coauthor {
				avatar();
				author_link(); // includes organization
				job_title();
				twitter();
			}
		}

		// add a separator to the output,
		echo '<span class="sep"> | </span>'
		// or we could do away with that and do it with only css

		published_date();
		edited_date();
			// if we aren't always displaying this, then the __construct function should be
			// a wrapper around an action, and the parts of the byline be methods,
			// which are hooked on that action. Child themes would be able to modify the action.

			// Or it should be a theme option, toggling the presence of the edit date,
			// but we're combatting massive growth of theme options.
		edit_link();
	}
	avatar() {} 
	author_link() {
		// apply the filters the_author and the_author_posts_link if we aren't using coauthors
	}
	job_title() {
		// there's a theme option toggling whether or not this is displayed
	}
	twitter() {}

	published_date() {
		// feeds arguments to largo_time
	}
	edited_date() {
	}
	edit_link() {
		// only displays if user can edit the post referenced
	}
}
```

**Comment by benlk** [comment]
1. base class should assume co-authors is not present, by default
2. Figure out how to modify the base class in case of co-authors, probably by extending the class to replace its actions with things that make sense for coauthors, then completely replacing the byline on the `largo_byline` filter, or just by having logic in `largo_byline` to do either `Largo_Byline`  or `Largo_Byline_CoAuthors`.

**Pull request closed without merging**
