### PR TITLE
Hide wp admin bar and sticky nav when using clean read

### PR DESCRIPTION
**Pull request by benlk**
## Changes

When the clean read mode is active, the sticky nav and the Wordpress admin bar shall hide, to prevent the "Exit Clean Read" button from being hidden.

## Questions:

- [x] How should this deal with the inevitable case where the exit link overlaps the text?

screen shot 2015-07-13 at 6 07 45 pm
screen shot 2015-07-13 at 6 08 23 pm

## Why?

The button was underneath all the sticky navigations. it wasn't clickable.

For #768.

### CODE REVIEW

**Comment by benlk** [comment]
Assigning this to @kaeti for feedback on how the "Exit Clean Read" button should display when it's layered over top of text in tablet-size viewports.

**Comment by benlk** [comment]
Notes:

- Make the background of the "Exit Clean Read" a full-width sticky nav, with opaque background.
- Use Javascript to hide the button when scrolling down or static, reveal when scrolling up. (This has been done before, but not in Largo)
- If that's too complicated, re-discuss with Kaeti.

**Comment by aschweigert** [comment]
I'd prefer to wait on the scroll to hide thing and address that for the sticky elements all at once (and with generally more thought, prototyping, user testing, etc.), probably just leaving is static/sticky for now is fine (for this one anyway). Let's make sure we have a ticket for the js behavior though for the sticky elements generally.

**Comment by benlk** [comment]
Then do we still want the full-width opaque background on the "Exit Clean Read" link, or should the background be limited to the area around the link, making it look like a button?

**Comment by benlk** [comment]
Or should there be a background at all, and this PR merged as-is?

**Comment by aschweigert** [comment]
full width opaque background still makes sense to me

**Comment by benlk** [comment]
I'll do that, then.

**Comment by kaeti** [comment]
Having two sticky nav elements on the screen at all times does not seem like a clean reading experience.

**Comment by aschweigert** [comment]
oh, is the main nav still present as well? sorry, i might be misunderstanding what this actually looks like in practice...

**Comment by kaeti** [comment]
The sticky footer is still present.

**Comment by aschweigert** [comment]
hm, what's the quick fix for this? I don't want to invest a ton of time in this featured since it's only really relevant for legacy sites (pre 0.4) anyway.

**Comment by kaeti** [comment]
We could put the "exit" link in the sticky footer (which isn't the most visible/user friendly option, but an option).

We could also try to force the link text fully into the margin by stacking the words and futzing with the width of the body content.

**Comment by aschweigert** [comment]
sticky footer makes most sense to me (for now)

**Comment by benlk** [comment]
screen shot 2015-07-14 at 1 17 27 pm

With the "exit" button in the sticky footer, should any of this stuff be hidden? (or all of it? :pray:)

**Comment by aschweigert** [comment]
the clean read option doesn't appear on mobile sizes at all, correct?

**Comment by benlk** [comment]
It does not appear at viewport widths of 768px or below, correct. The above image is a little wider than that, and the author doesn't have social media configured.

**Comment by aschweigert** [comment]
i'm fine with leaving everything else visible and just adding the "leave clean read" link for now

**Comment by aschweigert** [comment]
to explain what i mean by "for now" i think eventually share/follow should be links that only give the option to users (share where? follow what?) on click to clean this up a bit but that can come later, not worried about it for this particular ticket

**Comment by benlk** [comment]
Edge case: The sticky footer is not guaranteed to be visible.

- Sticky footer can be disabled
- Sticky footer can be closed by user, in which case Largo hides it and saves that preference in cookies.

**Comment by benlk** [comment]
screen shot 2015-07-14 at 2 17 16 pm

Now in the footer.

**Comment by rnagle** [comment]
Merged to `develop`: eb40a9c8597b6e3cae2a60fa24ccfad857a37048

**Pull request closed without merging**
