### PR TITLE
Removing some archive page styles from the top stories css

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Rules relating to archive display are removed from the homepage top story specific less file.
- Non-duplicated rules were added to archive.less

## Images:

Before, base Largo:

screen shot 2015-07-14 at 3 49 17 pm

After, base Largo

screen shot 2015-07-14 at 3 59 01 pm

Before, Wisconsin Watch theme

screen shot 2015-07-14 at 4 48 32 pm

Before, Wisconsin Watch theme
screen shot 2015-07-14 at 4 48 58 pm

## Why

> the styles for the top area of these hierarchical category pages are inexplicably in the less file for the "top stories" homepage layout (https://github.com/INN/Largo/blob/master/homepages/assets/less/top-stories.less#L87)

> Also, why is the background blue? Seems like the white background should just cover the primary/secondary featured area and any extraneous markup should be removed.

For #766

### CODE REVIEW

**Comment by benlk** [comment]
This does not currently address the issue where `/homepages/assets/css/top-stories.css` is enqueued on archive pages, with the slug `homepage-slider`.

**Comment by aschweigert** [comment]
do we have any idea why that would ever be necessary?

**Comment by benlk** [comment]
As far as I can tell, that css is never actually enqueued for archive pages. It's not showing up in Largo. It is showing up in JJIE for some reason.

**Comment by aschweigert** [comment]
it worries me that we don't know why that's happening...jjie is using that homepage layout, but that doesn't explain why it would be enqueued anywhere other than on the homepage...any thoughts on this one @rnagle?

**Comment by benlk** [comment]
With that homepage layout enabled in Largo, it doesn't show up. But with that homepage layout enabled in the jjie theme, it does show up. With a different layout enabled in JJIE, or with the same layout under Largo, it doesn't show up.

**Comment by rnagle** [comment]
The reason why homepage-related assets show up on not-the-homepage sometimes is because the `enququeAssets` method for the base `Homepage` class [doesn't check for `is_home`](https://github.com/INN/Largo/blob/master/homepages/homepage-class.php#L85).

I noticed this in the MWEN theme:

- CSS is included in the assets declaration [here](https://bitbucket.org/projectlargo/theme-midwestenergynews/src/a4b7765b9694085f100e70995e8c96043e8e08c0/homepages/homepage.php?at=master#cl-18)
- The JS used for the custom "load more posts" functionality was causing a conflict with the default Largo load more posts JS, so I had [include a hack of sorts](https://bitbucket.org/projectlargo/theme-midwestenergynews/src/a4b7765b9694085f100e70995e8c96043e8e08c0/functions.php?at=master#cl-46) to avoid said conflict.

Anyway, all that's just to (maybe, hopefully) lend some understanding.

I think it should be safe to change `enqueueAssets` to check for the homepage context before running.  We should definitely have a regression test prepped for this before we merge.

**Comment by rnagle** [comment]
Oh, I'd also say that the changes to the `Homepage` class should be a separate ticket. >_<

**Comment by benlk** [comment]
Changes in last commit: the secondary headline sizes decrease to 20px from 24px at browser sizes less than 960px wide.

This change comes in response to [Adam's comment here](https://github.com/INN/Largo/issues/766#issuecomment-121679574) on #766:

> smaller headline is probably fine as a quick fix. i think it would probably be best for them to eventually just match the format/style of the stories in the river below once it gets to a breakpoint where that makes sense

**Comment by benlk** [comment]
New issue created for that: https://github.com/INN/Largo/issues/791

**Comment by rnagle** [comment]
Merged: 5d84171fc635fc8d77ed00ae4b7a738e2c873dda.

**Pull request closed without merging**
