### PR TITLE
Add pullquote specific styles

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Updated the styling for pull quotes so they look different than normal block quotes.

**Before:**
Screen Shot 2019-07-15 at 9 06 13 AM

**After:**
Left:
Screen Shot 2019-07-12 at 4 29 23 PM

Right:
Screen Shot 2019-07-12 at 4 28 05 PM

Full-width:
Screen Shot 2019-07-12 at 4 30 32 PM

Wide:
Screen Shot 2019-07-12 at 4 30 08 PM

Normal:
Screen Shot 2019-07-12 at 4 31 45 PM

## Why

For #1699.

## Testing/Questions

Features that this PR affects:

- Pull quote blocks.

Questions that need to be answered before merging:

- [ ] Should we update any other styles for pull/block quotes?

Steps to test this PR:

1. Add a pull quote block to a post
2. Make sure it looks ok left aligned, right aligned, center aligned, and normal, wide, and full widths.

### CODE REVIEW

**Comment by benlk** [comment]
Previous work in this area: https://github.com/INN/largo/pull/1687

**Comment by benlk** [comment]
Those most-recent commits:

- Replace separate pullquote styles in https://github.com/INN/largo/pull/1746/commits/97495764a57b35acb227a1b24347cfbd6c60797c with adding the new `.wp-block-pullquote` class to the existing pullquote styles, similar to how https://github.com/INN/largo/pull/1687/files?file-filters%5B%5D=.less used the existing blockquote styles
- Moves all the pullquote styles shared between Classic and Block Editors from `posts-and-pages.less` to `typography.less`, where other blockquote styles live. Block-specific pullquote and blockquote styles remain in `blocks.less`.

**Comment by benlk** [comment]
An editor-specific style to override: the border-top and border-bottom on `wp-block-pullquote`.

Screen Shot 2019-07-16 at 16 09 01

**Comment by benlk** [comment]
I will note that https://github.com/INN/largo/issues/1748 was already broken in Largo; https://github.com/INN/largo/commit/be30571c2685540eb1e235a73618ea343c81761f just hides the borders in the editor.

@joshdarby do you think we should fix https://github.com/INN/largo/issues/1748 in this Largo release or in a later one? I wouldn't do it in this PR.

**Comment by benlk** [comment]
These changes are ready for review by someone not-me.

**Comment by joshdarby** [comment]
> @joshdarby do you think we should fix #1748 in this Largo release or in a later one? I wouldn't do it in this PR.

@benlk I'd prefer to get it done in this release since it is technically a bug, but since it was already broken... Has anyone complained specifically about not being able to specifically choose the color of the border? Worst comes to worst it can be edited by css by whoever wants to change it.

**Comment by joshdarby** [comment]
@benlk This still works as expected. Are you good with me merging it?

**Comment by benlk** [comment]
I haven't heard any user complaints about #1748 yet. Let's aim for putting that in the next release, and merging this.

**Pull request merged**
