### PR TITLE
Floating social buttons for single-column posts.

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Theme Option in Basic Options to enable floating social buttons: "Would you like to display share icons in a floating bar beside posts using the single-column post template?"
- New pluggable action function `largo_floating_social_buttons` run on `wp_footer` that outputs `largo_post_social_links()` inside a `<script type="text/template"`. This is pluggable to make it easy for child themes to change the buttons available.
- New pluggable action function `largo_floating_social_button_width_json` run on `wp_footer` that adds the minimum width which the floating social buttons should be displayed at. It's made pluggable to make it easy for child themes to configure.
- The viewport width in `largo_floating_social_button_width_json` is also run through the new filter `largo_floating_social_button_width_json`
- New pluggable action function `largo_floating_social_button_js` run on `wp_footer` to enqueue the javascript needed for the floating social buttons. If the javascript is not enqueued, then independent of the other two functions the floating social buttons will not display.
- CSS styling the floating social buttons grey, except on hover.
- Javascript! `js/floating-social-buttons.js`:
    - checks if the page is wide enough, and creates the social buttons if on the page if the page is wide enough. If the page is no longer wide enough, the social buttons are `opacity:0`. If the page becomes wide enough again, the social buttons become `opacity:1`. 
    - Positions the sticky buttons halfway up the page, and sets `opacity:0` if the page scrolls up to a point where the floating social buttons and the the header-or-hero would be visible at the same time, or if the page scrolls down to a point where one of several footer options would become visible: if the Largo Follow widget is in the article-bottom social area, or else the article-bottom widget, or else the footer.
- Minified version, `js/floating-social-buttons.min.js` that will be enqueued if `LARGO_DEBUG` is not true.

## Screenshots:

screen shot 2015-11-17 at 6 12 58 pm
screen shot 2015-11-17 at 6 13 48 pm
fsb-hover

## Debt

The scripts here aren't properly enqueued with WordPress' enqueue function in order to make them pluggable.

We're adding a bunch of styles just for the floating social button icon colors.

## To do

- [x] PHP tests
- [ ] Javascript tests?
- [x] Make `opacity:0` safe on narrowed browsers, so that people don't thumb invisible buttons.

### CODE REVIEW

**Comment by benlk** [comment]
This is Buzzfeed-style buttons: http://www.buzzfeed.com/reggieugwu/the-blessed-life-of-kaskade-edms-voice-of-reason#.xgnl5ybX7

They're fixed to the viewport. They float on top of other things. They disappear when they're not in use.

This is not CJR-style social icons, which move on the page and remain visible but confined to a certain area: http://www.cjr.org/united_states_project/michigan_bridge_magazine.php

**Comment by benlk** [comment]
PHP tests are complete and passing now.

**Comment by benlk** [comment]
Notes from post-scrum meeting today: 

- [ ] move the buttons up to 1 em below the sticky nav if it's there, or 1 em below the page top
- [ ] increase button size to greater than 48px*48px (minimum touch targets)
- [ ] add filter to largo_post_social_links on $output before the closing div tag, for proper

**Comment by benlk** [comment]
Post-scrum tasks are :white_check_mark:

**Comment by aschweigert** [comment]
for WE/RNS

**Pull request merged**
