### PR TITLE
Allow floating social icons on two-column and other post templates

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Removes the test of the post template when determining whether to output the floating social button template tag, javascript, and configuration JSON
- Adds that test back into the configuration JSON function `largo_floating_social_button_width_json`, to increase the minimum width of viewport needed for the floating social buttons when using a template other than Largo's single-column template
- Decreases the apparent spacing between the floating social buttons and the text column from `1` times the width of the floating social buttons to `0.7` times the width of the floating social buttons
- Recompiles minified javascript for the above change

## Why

For NPQ and [VO-10](http://jira.inn.org/browse/VO-10), because we removed the sticky footer in 0.5.4.

### CODE REVIEW

**Comment by benlk** [comment]
Questions:

- [ ] are there any child themes that define their own templates with page column-widths differing from Largo's 1170px?
- [ ] what child themes should this be tested against?

**Comment by aschweigert** [comment]
do we need any additional styling for this to make sure it gets positioned correctly? wasn't the reason we pulled it originally because it was appearing over the content in some cases?

**Comment by aschweigert** [comment]
as far as i know there are no child themes we host, using 0.5.4, that alter the overall page width from the 1170px default

**Comment by aschweigert** [comment]
i WOULD like to take a quick look at this on staging though, for all of the sites using the two column layout

**Comment by benlk** [comment]
It was a worry. 

I've checked this against posts in themes with different single templates:

- current
- npq
- voiceofoc
- gijn-impact

There haven't been any problems so far. The buttons are positioned outside the main page container div, so there haven't been conflicts.

**Pull request merged**
