### PR TITLE
Replace all Largo Featured Posts widgets with Largo Recent Posts widgets

### PR DESCRIPTION
**Pull request by benlk**
#897 needs to wait until *after* this Pull Request has been deployed and update functions have been run.

## Changes

- Internal documentation for `largo_replace_deprecated_widgets`
- When `largo_replace_deprecated_widgets()` runs:
    - `largo-footer-featured` widgets will be replaced with `largo-recent-posts` widgets instead of `largo-featured` widgets
    - `largo-sidebar-featured` widgets will be replaced with `largo-recent-posts` widgets instead of `largo-featured` widgets
   - `largo-featured` widgets will be replaced with `largo-recent-posts` widgets
- Updated the tests for `largo_replace_deprecated_widgets()`

## To do

- [x] beyond the tests working, check this actually works in a production context
- [x] check tests accurately capture misc options being passed from widget to widget
- [x] Callback option for updates
- [x] check the featured posts widgets don't have conflicting args with the Largo Recent Posts widget
- [ ] Check for child themes that have styles for featured posts widgets; those that do will need those styles adjusted to `.largo-recent-posts`:
    - `.largo-featured`,
    - `.largo-footer-featured`,
    - `.largo-sidebar-featured`

## Why

For #982, because the Largo Featured posts widget was just duplicating the Largo Recent Posts widget functionality.

### CODE REVIEW

**Comment by benlk** [comment]
This PR still needs a lot of work, but I'm filing it now with a long to-do list.

**Comment by benlk** [comment]
Regarding "check tests accurately capture misc options", this doesn't do that. It passes $instance, but sometimes $instance variables don't match, so I'm creating a callback option here.

**Comment by benlk** [comment]
Is it possible to have the widget files still be there, and allow the widgets to run if they're added, but not show the widgets in the widgets list?

We can't remove the widget files until after the migration is run, for the reasons listed in #897.

**Comment by benlk** [comment]
Should the recent post widgets's options be added as classes on the widget? That way, it would be possible to style widgets depending on the prominence taxonomy term, to match previous featured post widget styles in child themes.

**Comment by aschweigert** [comment]
I would rather just remove/update the styles in child themes, don't want to prolong this agony for too long, better to just clean it up once and move on

**Comment by rnagle** [comment]
Merged to `develop` in d223b0b4cb5d90b23aa409fb32870f7ce559e218.

**Comment by benlk** [comment]
Time checking child themes should be logged in http://jira.inn.org/browse/LAR-27

**Pull request closed without merging**
