### PR TITLE
Update footer INN logos

### PR DESCRIPTION
**Pull request by tylermachado**
This adds in two new files for the updated INN logo, in the new blue (when on light backgrounds anyway).

Closes https://github.com/INN/largo/issues/1631

### CODE REVIEW

**Comment by benlk** [comment]
Is it possible to optimize those images even more than their current filesize allows?

**Comment by tylermachado** [comment]
I thiiiink I tried to get them as small as possible? Considering for pixel size and transparency, at least

**Comment by benlk** [comment]
I converted these from color PNG to indexed PNG, with max 127-color palettes, and got the image sizes way down. Can you take a look and see if these images are acceptable?

35K inn_dark.png [inn_dark](https://user-images.githubusercontent.com/1754187/52675560-373b2900-2ef5-11e9-88e3-52e633c9e6ca.png)  (original)

7.5K inn_dark-ex.png [inn_dark-ex](https://user-images.githubusercontent.com/1754187/52675550-30acb180-2ef5-11e9-8cff-1f7824881e23.png) — just as harshly aliased as the `inn_light-ex` logo below, but perhaps less apparent on the backgrounds i've been previewing on.

32K inn_light.png [inn_light](https://user-images.githubusercontent.com/1754187/52675570-402bfa80-2ef5-11e9-9468-e56c66c3f14e.png)  (original)

9.8K inn_light-ex.png [inn_light-ex](https://user-images.githubusercontent.com/1754187/52675564-3bffdd00-2ef5-11e9-9cd0-0662119da1ff.png) — harshly aliased, but we're usually showing these images at much lower display sizes than their intrinsic size.

**Comment by tylermachado** [comment]
I inserted those into my local install and I felt like the aliasing was noticeable even at a width of about 300px. Maybe because I was just looking for it going in? That said ... what if we reworked the code a touch so that it took an SVG instead?

**Comment by benlk** [comment]
https://caniuse.com/#feat=svg

Switching to SVG would be awesome.

**Comment by tylermachado** [comment]
Ok, made SVG files for this round. I embedded the SVGs in  tags -- the PHP file_get_contents() method was throwing SSL errors that I couldn't decode, and I'm not sure how that'd play with the suggestion to use functions.php to swap the colors out.

**Comment by benlk** [comment]
Merged latest 0.5-dev branch into this, updated a line of docs, updated the changelog.

Notes on page size, with `INN_MEMBER` set to `true`:
- before this PR, 251 KB
- in this PR, 248 KB

Questions which we should think about before merging this PR:

- Would we still want to include the .png files in Largo? The ones introduced by earlier commits in this branch are kept by the commits that added the .svg files; should we keep the .png files around as reference images or just remove them?
- Should any of the documentation here link to INN's brand standards? If so, should these docs include a request that, if someone notices a discrepancy between the brand standards and Largo, that that person file an issue in this repo or send an email?

**Pull request merged**
