### PR TITLE
Import NPQ mobile nav styles into Largo

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This copies over the NPQ styles into Largo.

- Carets point right before drop-downs are opened, and then point down.
- Third-level and fourth-level menu items are hidden more forcefully
- Highlights on active and hovered menu items are removed *on mobile only*
- Menu hamburger becomes dark on light, using the standard link color for the bars. Previously, this had used the link color for the box and white for the bars.
- Text and carets in sticky nav are now all using the standard link color.
- Remove all styles pertaining to `.nav-middle` and `.nav-collapse`, which were not found in any Largo HTML, PHP, CSS, or JavaScript.

Before (Using plain Largo)

screen shot 2015-08-24 at 7 31 39 pm
screen shot 2015-08-24 at 7 31 46 pm
screen shot 2015-08-24 at 7 31 55 pm

After:

screen shot 2015-08-24 at 7 30 06 pm
screen shot 2015-08-24 at 7 30 21 pm
screen shot 2015-08-24 at 7 30 36 pm
screen shot 2015-08-24 at 7 30 54 pm

## To do

- [x] check child themes
    - [x] NPQ (Customized)
    - [x] Voice of OC (Uses a bright Yellow, also heavily customized)
    - [x] Current.org
    - [x] City Limits
    - [x] Youth Today
    - [x] Catalyst Chigao - will rpobably need custom work on .icon-bars
    - [x] Where else have we done heavy header customization?
- [x] check other browsers
    - [ ] IE
    - [x] Safari
    - [x] Firefox
    - [ ] Old Android
- [x] create post-deploy list of sites to update, and what updates they need

## Why

For [SN-4](http://jira.inn.org/browse/SN-4) and #807. (See also #732)

### CODE REVIEW

**Comment by benlk** [comment]
- [ ] check child themes
    - [ ] NPQ (Customized)
        - Needs branch largo-sn-4-update to continue looking good: 
screen shot 2015-08-28 at 3 00 38 pm

    - [x] Voice of OC (Uses a bright Yellow, also heavily customized)
        - Needs branch largo-sn-4-update to continue looking good: 
screen shot 2015-08-28 at 1 50 05 pm

    - [x] Current.org
        - needs branch largo-sn-4-update to continue looking good:
screen shot 2015-08-28 at 2 11 34 pm

    - [x] City Limits: heavily customized, but works fine with this update:
screen shot 2015-08-28 at 3 20 59 pm


    - [x] Youth Today: good to go:
screen shot 2015-08-28 at 3 29 43 pm

    - [ ] Catalyst Chigao: needed some styles overridden to match what we have now:
        - needs branch largo-sn-4-update to continue looking good:
screen shot 2015-08-28 at 3 45 38 pm

    - [ ] Where else have we done heavy header customization?
- [ ] check other browsers
    - [ ] IE
    - [ ] Safari
    - [ ] Firefox
    - [ ] Old Android

**Comment by benlk** [comment]
As usual, all sites using the CSS customizer will need to have their stuff recompiled.

Some more checks:

- [x] jjie.org should probably go on the custom CSS variables, with the primary and link colors set to `#9c0001`, instead of using theme CSS to change those colors:
screen shot 2015-08-28 at 5 24 56 pm
-  [x]  necir.org
    - will need to move to branch largo-sn-4-update to continue looking good:
screen shot 2015-08-28 at 5 46 44 pm
- [x] ijec.org: custom LESS
- [x] aspenjournalism.org: Appears to have disabled the sticky nav
- [x] invw.org: doing its own thing
- [x] raleighpublicrecord.org: :+1: stock Largo
- [x] newsdesk.org: Custom LESS, plain stylesheet.
- [x] mtcir.org: Custom LESS
- [ ] inewsnetwork.org: Custom LESS, no sticky nav, custom menu partial that isn't collapsing well.
- [x] citylimits.org: see above
- [x] kycir.org: no sticky nav. no custom LESS. :+1:
- [ ] chicago reporter: Needs theme work.

----

And that's as far as I've gotten today.

**Comment by aschweigert** [comment]
kycir and inewsnetwork are still 0.3 (updating soon, hopefully) and so is aspen journalism (updating soon, for sure). Make sure if you're doing this kind of testing that we're only checking sites that are actually using 0.5.2+ so we're not wasting too much time checking sites we're going to rebuild soon anyway.

**Comment by benlk** [comment]
Here's the list of sites on production, and whether their themes have been checked or not: https://docs.google.com/spreadsheets/d/11VMk3kMz1S_eGzkJj6c8_MBlHqZFX6AssfpngrnB2Zs/edit#gid=0

This also includes a general overview of trouble points, with my best guess at coloration for whether things are normal :green_book:, something to look out for :yellow_heart:, or something to actively check for :red_circle:.

**Comment by benlk** [comment]
@rnagle I'm going to update this branch from develop. The last common commit between this branch, master, and develop was master's 4f2890bcc08f6516f5df2dd24bc5220e9c5aa613.

**Comment by benlk** [comment]
For all the sites that I know have All the child themes have been checked out, with branches created as appropriate: https://docs.google.com/spreadsheets/d/11VMk3kMz1S_eGzkJj6c8_MBlHqZFX6AssfpngrnB2Zs/edit#gid=0

I think this is safe to merge

**Comment by aschweigert** [comment]
i think probably let's go ahead and get this merged before we do anything else given the potential for mega conflicts

**Comment by benlk** [comment]
This should be merged to develop.

Not sure why I filed this against master in the first place. :confused:

**Comment by benlk** [comment]
Closing in order to refile against master.

**Pull request closed without merging**
