### PR TITLE
Related Posts widget: make byline and thumbnail placement options work

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- "show date" option text is renamed to "show byline" to match internal variable
- `show_byline` option now actually toggles the presence of the byline; defaults to not
- ~~Before/After headline option for thumbnail placement now has effect~~
- ~~Styles for proper alignment of thumbnail in before and after positions~~

## Why

Because we had these options in the widget, but they weren't doing anything.

For #1242

### CODE REVIEW

**Comment by aschweigert** [comment]
Is the before/after option for the thumbnail a thing we actually want/need? Seems overly complicated for me unless there's a particularly good reason for it.

**Comment by benlk** [comment]
I'm in favor of removing it. It is a needless complication, and it makes more sense for that to be a child-theme styles decision than a per-widget decision.

**Comment by aschweigert** [comment]
go for it

**Comment by benlk** [comment]
D we want an option to disable showing the thumbnail at all?

**Comment by benlk** [comment]
Before/After option and styles have been removed.

**Comment by aschweigert** [comment]
the markup that uses that option is still in the widget though...right?

**Comment by benlk** [comment]
Not sure what you mean by "the markup that uses that option" - the only difference to the markup on the thumbnail and the link inside it is that the thumbnail no longer has an `alignleft` class on it, and instead gets the `float: left` from the widget's styles.

**Comment by aschweigert** [comment]
I see, there was just a comment in there that made it look like that option was still present. Removed that and I think we're fine to merge this.

**Pull request merged**
