### PR TITLE
Navis Slideshow expand-on-click styles, again.

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- [x] Implements https://github.com/INN/largo/issues/1664#issuecomment-486421174:
    - makes sure Gutenberg image captions don't display in Navis slideshows
    - makes sure global nav falls under the Navis image presentation
    - fixes alignment for images
- [x] hides sticky nav when opening Navis slideshow
- [x] update changelog for this
- [x] bumps Largo version number to 0.6.3-pre

Testing to be completed pre-merge:

- [x] on MST: works locally; staging experienced a deploy problem with git push and we're talking with the host.
- [x] on C
- [x] fullwidth block
- [x] align left/right/center/none block
- [x] gallery block?
- [x] Classic Editor slideshow gallery shortcode
- [x] Featured Gallery in Largo

### CODE REVIEW

**Comment by benlk** [comment]
Bug that appeared in testing: An image in a block that's aligned full will revert to single-column width when the gallery closes.

Before:
Screen Shot 2019-04-25 at 12 20 33

```html
<figure class="wp-block-image alignfull"><img src="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg" alt="Two genders do the bopping" class="wp-image-129823" srcset="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg 1170w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-336x224.jpg 336w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-768x512.jpg 768w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-771x514.jpg 771w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h.jpg 1600w" sizes="(max-width: 1170px) 100vw, 1170px"><figcaption>This is a full-width image. It should be preceded by a single paragraph tag.</figcaption></figure>
```


Upon click:
Screen Shot 2019-04-25 at 12 20 36

```html
<figure class="wp-block-image alignfull navis-slideshow navis-single navis-full" style="max-width: 100%;"><span class="navis-before">X</span><img src="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg" alt="Two genders do the bopping" class="wp-image-129823" srcset="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg 1170w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-336x224.jpg 336w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-768x512.jpg 768w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-771x514.jpg 771w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h.jpg 1600w"><figcaption>This is a full-width image. It should be preceded by a single paragraph tag.</figcaption></figure>
```

After closing:
Screen Shot 2019-04-25 at 12 20 41

```html
<figure class="wp-block-image alignfull" style="max-width: 100%;"><img src="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg" alt="Two genders do the bopping" class="wp-image-129823" srcset="http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-1170x780.jpg 1170w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-336x224.jpg 336w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-768x512.jpg 768w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h-771x514.jpg 771w, http://mstoday.test/wp-content/uploads/2018/02/24496652921_1108fff3b7_h.jpg 1600w" sizes="(max-width: 1170px) 100vw, 1170px"><figcaption>This is a full-width image. It should be preceded by a single paragraph tag.</figcaption></figure>
```

---

This appears to be because `style="max-width: 100%;"` is added to the gallery parent in the initial click:

https://github.com/INN/largo/blob/c487ba7b2ec3b455cc519f4f85421c3dcc310bf0/lib/navis-slideshows/js/navis-slideshows.js#L231-L240

But I'm not sure why the `gallery.attr` call in the close handler isn't removing the style attribute:

https://github.com/INN/largo/blob/c487ba7b2ec3b455cc519f4f85421c3dcc310bf0/lib/navis-slideshows/js/navis-slideshows.js#L145-L155

**Comment by benlk** [comment]
The `attrs` argument passed in this case are:

```
 ["(max-width: 1170px) 100vw, 1170px", undefined, undefined, undefined]
```

which based on the docs in https://api.jquery.com/attr/#attr2, appears to be undefined behavior when `undefined` is passed as the value for `.attr( attributeName, value )`. 

- [x] if typeof value === 'undefined': value = null;

**Comment by benlk** [comment]
@joshdarby this is ready for review

**Comment by benlk** [comment]
Are we worried that the user can scroll the page when the popup is open, and can thereby trigger the sticky nav to appear, covering the slideshow's close button?

**Comment by joshdarby** [comment]
> Are we worried that the user can scroll the page when the popup is open, and can thereby trigger the sticky nav to appear, covering the slideshow's close button?

@benlk I'd think we'd probably want to disable scrolling when the popup is triggered. That might also help with our other issues of overlapping menus and whatnot.

**Comment by benlk** [comment]
Also, with a Gallery block, the image is cropped:

Screen Shot 2019-04-25 at 13 36 19

Screen Shot 2019-04-25 at 13 36 14

**Comment by benlk** [comment]
Current to-do list:

- [x] stop scroll when the modal is open from an image block
- [x] stop scroll when the modal is open from a gallery block
- [x] stop scroll when the modal is open from post featured gallery
- [x] prevent overzoom of images when modal is open from a gallery block

**Comment by benlk** [comment]
Gallery Block has margin-left:

Screen Shot 2019-04-25 at 14 02 21

- [x] CSS fix for this

**Comment by joshdarby** [comment]
@benlk One more issue with this that I noticed is that if you have an image expanded and start to resize the window, the sticky nav pops up again. Maybe we should add a check to it to not display if any `figure` has the `.navis-full` class.

**Comment by benlk** [comment]
Or we should change the hide/show functions in this JS to hide a parent of the sticky nav element that's currently being shown/hidden.

**Comment by benlk** [comment]
Regarding the gallery image cropping, this isn't a JS fix; it's a CSS fix for this monstrosity of a default style:

```css
.wp-block-gallery.is-cropped .blocks-gallery-image a,
.wp-block-gallery.is-cropped .blocks-gallery-image img,
.wp-block-gallery.is-cropped .blocks-gallery-item a,
.wp-block-gallery.is-cropped .blocks-gallery-item img {
    height: 100%;
    flex: 1;
    -o-object-fit: cover;
    object-fit: cover;
}
```

The 100% height I'm not sure we should change, but looking at [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) we could use `object-fit: scale-down;` so that small images aren't blown up and large images don't overflow.

[object-fit doesn't work in IE](https://caniuse.com/#feat=object-fit) though, which is probably why the 100% height.

**Comment by joshdarby** [comment]
@benlk One more: On the [sandbox](https://demo.innsandbox.wpengine.com/2019/04/25/block-unit-test-one-column-post/), whenever I click to expand an image inside the `Full Width Gallery Block`, I just get a white screen with no exit button.

**Comment by benlk** [comment]
> a white screen with no exit button.

Is that from clicking on one of the light-grey images? 

If it is, and if this is a contrast issue, should we do something to make sure that this X is more visible?

Screen Shot 2019-04-25 at 14 38 45

**Comment by benlk** [comment]
Nope, this is not just a contrast issue.

- [x] image in full width gallery block,
- [x] "at if you have an image expanded and start to resize the window, the sticky nav pops up again. " change the show/hide element on the sticky nav

**Comment by joshdarby** [comment]
> Is that from clicking on one of the light-grey images?
> 
> If it is, and if this is a contrast issue, should we do something to make sure that this X is more visible?

@benlk Yes, I did click on one of the light gray images but I don't believe it's a contrast issue. If you click on one of the light gray images above in the `Three Column, Four Images` block, you're still able to see the exit button.

I also tried replacing one of the images with a darker image and it still showed a white screen with no exit.

**Comment by benlk** [comment]
Wit that white-page error, there are clearly elements on the page:

Screen Shot 2019-04-25 at 14 53 11





They're just ... not showing up?

**Comment by joshdarby** [comment]
@benlk I think it's the `transform` attribute on the `.alignfull` class on the parent `wp-block-gallery` messing with it. Removing that attribute will make the image appear.

**Comment by benlk** [comment]
The transform problem here is another instance of https://github.com/INN/largo/pull/1685, which means that we need a general solution for this. Which should be doable.

**Comment by benlk** [comment]
Hmm, the change in https://github.com/INN/largo/pull/1695/commits/4ddfab09f75bdbd9a7e8b491fd49f2f222e5aa95 doesn't seem to have taken when I deployed that to staging.

- [x] cachebusters ahoy!

**Comment by benlk** [comment]
Note: When pushing LESS changes, remember to go to Dashboard > Appearance > CSS Variables and click "Save Variables".

**Comment by benlk** [comment]
A thing that may help to understand code flow in the slideshow js:

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmllb1tpbWcuZWFjaCBvbmNsaWNrXVxuaXNfdXNlcl9sb2dnZWRfaW5cbm1heWJlSGlkZVN0aWNreU5hdlxubWF5YmVTaG93U3RpY2t5TmF2XG5ib2R5U3RvcFNjcm9sbFxuYm9keVN0YXJ0U2Nyb2xsXG5jcmVhdGVTbGlkZXJcbmNyZWF0ZVNsaWRlci0tPmV4cGFuZFNsaWRlclxuY3JlYXRlR2FsbGVyeS0tPmNyZWF0ZVNsaWRlclxuY3JlYXRlR2FsbGVyeS0tPmFkZENsb3NlWFxuYWRkQ2xvc2VYLS0-Y2xvc2VGdWxsXG5leHBhbmRTbGlkZXItLT5tYXliZUhpZGVTdGlja3lOYXZcbmV4cGFuZFNsaWRlci0tPmJvZHlTdG9wU2Nyb2xsXG5leHBhbmRTbGlkZXItLT5hZGRDbG9zZVhcbmNsb3NlU2luZ2xlLS0-bWF5YmVTaG93U3RpY2t5TmF2XG5jbG9zZVNpbmdsZS0tPmJvZHlTdGFydFNjcm9sbFxuY2xvc2VGdWxsLS0-Y3JlYXRlU2xpZGVyXG5jbG9zZUZ1bGwtLT5hZGRDbG9zZVhcbmNsb3NlRnVsbC0tPmNsb3NlU2luZ2xlXG5cbmVzY2FwZXtkb2N1bWVudC5rZXl1cCBlc2NhcGV9XG5lc2NhcGUtLT58aWZ8aXNfdXNlcl9sb2dnZWRfaW5cbmVzY2FwZS0tPmNsb3NlRnVsbFxuXG5kb2N1bWVudC5yZWFkeXtkb2N1bWVudC5yZWFkeX0tLT5pbWcuZWFjaFxuaW1nLmVhY2gtLT58aWZ8aXNfdXNlcl9sb2dnZWRfaW5cbmltZy5lYWNoLS0-bWF5YmVIaWRlU3RpY2t5TmF2XG5pbWcuZWFjaC0tPmJvZHlTdG9wU2Nyb2xsXG5pbWcuZWFjaC0tPnxpZiB1bmxpbmtlZCBpbWFnZXxpZW9cbmllby0tPm1heWJlU2hvd1N0aWNreU5hdlxuaWVvLS0-Y2xvc2VTaW5nbGVcblxuZG9jdW1lbnQucmVhZHktLT4ubmF2aXMtc2xpZGVzaG93LmVhY2hcbi5uYXZpcy1zbGlkZXNob3cuZWFjaC0tPnxoYXNDbGFzcyBub25lLXVwfHNsaWRlc2hvd1xuc2xpZGVzaG93LS0-Y3JlYXRlU2xpZGVyXG4ubmF2aXMtc2xpZGVzaG93LmVhY2gtLT58ISBoYXNDbGFzcyBub25lLXVwfGdyaWRcbmdyaWQtLT5jcmVhdGVHYWxsZXJ5IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Pull request merged**
