### PR TITLE
largo social update

### PR DESCRIPTION
**Pull request by dryanmedia**
* icons now sized in author box appropriately for a person with fingers to touch them on a touch screen
* widget functional purely with links
* variables created for social media icons to remove headaches (and implemented where colors used)
screen shot 2015-07-01 at 5 06 37 pm
screen shot 2015-07-01 at 5 06 07 pm

### CODE REVIEW

**Comment by dryanmedia** [comment]
This is in reference to INN/Largo#741

**Comment by rnagle** [comment]
This looks great.

We're going to need a plan for rolling this out, since some of our child themes have styles applied to these elements.

For example, current.org will look broken when we merge and deploy this:

image

image

**Comment by aschweigert** [comment]
i think we should just remove the custom styles from child themes and use the defaults, it's silly to have to maintain a bunch of different variations for something so trivial

**Comment by aschweigert** [comment]
also, it looks kind of weird with the email icon a different size/shape than the others (in the author profile), can we do something about that?

**Comment by dryanmedia** [comment]
Ok So to do:
* [ ] make email icon more uniform
* [ ] identify sites where this might break
* [ ] remove cruft from child themes

Anyone have thoughts about how I'd go about identifying Largo sites that have CSS modifying the buttons?

**Comment by rnagle** [comment]
@dryanmedia You're probably going to have to look at each child theme to see if there are any related styles. I would start by checking the front-end of each site using 0.4+ to see if the social media icons/buttons look in anyway non-standard. That's the best advice I have, unfortunately.

**Comment by dryanmedia** [comment]
Update
- [ ] current.org pull ready-to-go
- [ ] chicagoreporter.com now lessified, needs pull

Keep an eye on:
- Kentucky CIR
- InvestigateWest
- Midwest Energy News
- CTMirror.org
...

**Comment by aschweigert** [comment]
@dryanmedia it's been a while since we've looked at this, is there still a PR open? if so it probably needs a little work to avoid merge conflicts.

**Comment by dryanmedia** [comment]
ugh I'm going to be closing this branch, I don't see any conflicts in this branch and even when I reprocess less I'm getting. I will comment with new pull # when I close
screen shot 2015-09-04 at 1 04 12 pm
 this

**Comment by dryanmedia** [comment]
See #890

**Pull request closed without merging**
