### PR TITLE
Search page improvements

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Search results pages gain the `archive` class to get a lot of the styles we use in term archives.
- Search results lose some custom per-article styles.
- Default Largo search form in the main column of the search results page now has markup matching the header search form.
- Search form in the main column of the search results page is now 100% width of column, with submit button at 10% width and the input at 90%. Also added: `0.5em` padding-bottom, 1px dark grey border-bottom, 1em margin-bottom to put some space between the header and the results.
- Excerpts in the `content-search` partial now default to 2 sentences instead of 5, matching the limits used elsewhere in Largo. (Not shown in the screenshots below.)

screen shot 2016-03-08 at 1 04 49 pm
screen shot 2016-03-08 at 12 53 11 pm

## Why

For #1162 and [RNS-198](http://jira.inn.org/browse/RNS-198).

### CODE REVIEW

**Comment by benlk** [comment]
Julia, what feedback do you have?

**Comment by aschweigert** [comment]
the mobile view is a little odd with the search icon in the header and then the search box...we probably don't need both. I'd also consider slimming the results down even a bit more, probably no top tag, maybe no byline, a very short excerpt if possible. Smaller headline (probably), generally just make this a bit more compact and more search results-y

**Comment by benlk** [comment]
I dunno, I think the longer excerpt is better for search results, in helping people find what they're looking for. Shorter excerpts feel clickbaity.

- [ ] is removing the search icon in the header possible without a hideous conditional/css?
- [ ] remove top tag
- [ ] comment out byline (leaving placement there in case child themes want the byline)

**Comment by benlk** [comment]
screen shot 2016-03-08 at 4 36 39 pm
screen shot 2016-03-08 at 4 36 52 pm

**Pull request merged**
