### PR TITLE
Add date and link to the search results partial

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Adds date above the excerpt, in a `small.date` element
- Adds the permalink to the search results, below the excerpt
- Styles the date grey

Using wenews:

screen shot 2016-03-18 at 6 16 31 pm
screen shot 2016-03-18 at 6 16 39 pm

## Why

[RNS-198](http://jira.inn.org/browse/RNS-198).

### CODE REVIEW

**Comment by aschweigert** [comment]
I would prefer date and link both below the except, so:

Headline
Excerpt
Date | URL

**Comment by aschweigert** [comment]
also tighten up the space before/after the excerpt, just make that the same visual space as we have between the lines of text in the excerpt

**Comment by benlk** [comment]
Paragraph margin-bottom to 0, "Date | url" in play:

screen shot 2016-03-22 at 5 46 21 pm
screen shot 2016-03-22 at 5 46 34 pm

**Comment by aschweigert** [comment]
headline is probably a touch big on larger screens, let's merge and see where we're at

**Pull request merged**
