### PR TITLE
Add an @see for this reference, because we're blind.

### PR DESCRIPTION
**Pull request by benlk**
## Changes

Adds a reference to a docblock, because two devs who went looking didn't find the referenced thing.

## Why

Because we couldn't find the thing.

### CODE REVIEW

**Comment by aschweigert** [comment]
let's add the actual path/file where this can be found since it doesn't seem to be anywhere where we'd actually reasonably go looking for it (or we should move it to somewhere more sensible)

**Comment by benlk** [comment]
The referenced function is the function directly above this one in the file.

**Comment by aschweigert** [comment]
this looks worse than it is, mostly just moving a couple functions to more logical places + cleaning up some formatting. The largo series list widget has since been reworked in develop (i think/hope) so we'll want to make sure the function name I changed is updated there as well (largo_featured_thumbnail_in_post_array -> largo_first_thumbnail_in_post_array)

**Comment by aschweigert** [comment]
really, this should all be merged to develop, this doesn't make sense as a hotfix directly to master

**Comment by aschweigert** [comment]
closing in favor of #1278

**Pull request closed without merging**
