### PR TITLE
Refactor the most recent widget

### PR DESCRIPTION
**Pull request by willhaynes**
- [x] Recent posts now outputs one consistent dom type (unordered list).
 - [x] Added new image alignment setting.
 - [x] Removed medium image option (it outputs the same as large image)
 - [x] Commented widgets.less
 - [x] Fixed padding issues.

### CODE REVIEW

**Comment by willhaynes** [comment]
Before we merge in, it might be worth looking at with @kaeti to see if we can make some immediate UI improvements for 0.5.

Here's what a couple configurations look like.

# #1 

image

# #2 

image

# #3

image

# #4 

image

# #5 

image

**Comment by rnagle** [comment]
@willhaynes This looks good to me. I notice that there are changes to `widgets.less` but no corresponding css file was changed. Do we need to recompile any css for this?

**Comment by willhaynes** [comment]
Yeah. I didn't commit css to avoid merge conflicts.

**Comment by rnagle** [comment]
Cool. Feel free to commit the CSS in the future. Since presumably we're not editing those files directly, any merge conflict can be fixed with `grunt less`.

**Pull request merged**
