### PR TITLE
Continued byline changes

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Creates new conditional function `largo_post_was_updated( $post )` in `inc/conditionals.php`
- Uses `largo_post_was_updated` in `Largo_Byline` and its inheritor classes to determine whether to show the published date or the updated date
- Updated date is only show if the post was updated and if the byline is being displayed in the context `is_single()`
- The updated date now uses a `<time>` element, to match the published date
- Removes the `h5.top-time` time element from the single post template, and styles for it
- Removes styles hiding the date in the single-post and single-page bylines

## Why

For #1259, continuing #1126.

For the Rivard Report.

### CODE REVIEW

**Comment by aschweigert** [comment]
so is the behavior here that we show either the updated date OR the published date but not both? are we still doing the XX hours ago for posts published/updated in the last 24 hours? or just posts *published* in the past 24 hours?

**Comment by benlk** [comment]
Here's what shows:

 | published within 24 h | published more than 24h ago
:-- | :-- | :--
Updated | Shows updated date | Shows updated date
Not updated | Shows the `largo_time` "XX hour ago" format | Shows the published date

**Comment by benlk** [comment]
> let’s make the updated date also do the XX hrs ago thing
> and then that’s fine to merge i think
> some sites may want to show published and updated
> but this should be the default

- [ ] updated date in the XX Hours Ago format, as new function `largo_time_updated`

**Comment by aschweigert** [comment]
lgtm, passing this to @rclations for a second set of eyes and then let's merge

**Comment by rclations** [comment]
everything looks good to me!

**Comment by benlk** [comment]
And the failing tests are the usual, so I'll merge this and deploy it to Rivard.

**Pull request merged**
