### PR TITLE
Remove explore related widget

### PR DESCRIPTION
**Pull request by aschweigert**
This should have been deprecated already and I'm not particularly worried about explicitly covering this with an update script since so few sites are affected and we've already manually updated our sites. Anywhere else in Largo we'd need to lose this to remove it once and for all?

### CODE REVIEW

**Comment by benlk** [comment]
- [ ] remove widget
- [ ] remove idTabs.js
- [ ] remove styles for above

**Comment by aschweigert** [comment]
@benlk those things are all included in this PR, just wondering about anything else?

**Comment by benlk** [comment]
Yeah, sorry, I misread this as an issue and not as a PR, and copied some stuff over.

There's a test in the update tests that needs to be updated, to remove a reference to this widget:

```
tests/inc/test-update.php:141:           $this->assertEquals('largo-explore-related-widget-2', $widgets['article-bottom'][4]);
```

Translation files mention this plugin, but those can be rebuilt at a later date (before releasing the next version of Largo) because they're prone to merge conflicts and are terrible.

**Comment by aschweigert** [comment]
@benlk can you resolve any conflicts with develop so we can review and merge this? anything else that's still needed here?

**Comment by benlk** [comment]
Nope, updating it with the latest develop and updating a test was it. There's some CSS conflicts, which are what affect mergeability.

The other failing tests are the ones that should be addressed in https://github.com/INN/Largo/issues/1188

**Comment by rclations** [comment]
looks good to me

**Pull request merged**
