### PR TITLE
Sticky nav menu will now shove overflow into a 'More' dropdown

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Adds @willhaynes' [function to add sticky nav overflow to an overflow menu](https://bitbucket.org/projectlargo/theme-current/src/5000fb416ead5788d1f5e5c9ce0db2d6dd842493/js/current.js?at=master) to largoCore.js
    - One major addition: if there is no suitable dropdown menu in the sticky nav, create one.
- Rebuilds largoCore.min.js

## Reasoning

For NQ-81 and #376: Sometimes there's just too much stuff in the header, and it ends up wrapping around.

## Conflicts

- Some users may complain that menu items are being hidden. They probably had too many items in the main Largo menu area.

### CODE REVIEW

**Comment by benlk** [comment]
Problem: This doesn't work with normal nested menus. It only works with completely flat menus.

- Child menus in the overflow menu cannot be opened.
- Child menus in the overflow menu cannot be closed.

Proposed solution: child menus are always visible, in-line, in the dropdown menu, without needing to hover or open the child menu.

**Comment by aschweigert** [comment]
@benlk can you point me to an example of what you mean? I think maintaining some feeling of hierarchy here would be important so many we can come up with some other alternatives.

**Comment by benlk** [comment]
Using the menu structure:

- news
- fundraising
- philanthropy
- management
    - management child
- policy
    - customer support
- opinion
    - commments
- resources
    - advertise
    - webinars
- store

and narrowing the screen, the following is obtained:

screenshot - 05142015 - 10 49 19 am

- news
- fundraising
- philanthropy
- management
    - management child
- more
	- policy
		- customer support
	- opinion
		- policy
			- customer support
		- commments
	- resources
		- opinion
			- policy
				- customer support
			- commments
		- advertise
		- webinars
	- store

Apart from the submenu duplication problem, the submenus visually overlap the main menu. They should either be placed to one side of the main menu (ick) or be immediately visible:

screenshot - 05142015 - 11 04 54 am

(again, ignoring the duplication)

**Comment by aschweigert** [comment]
so...part of the problem here is that that menu structure is insane and not something that anyone should ever do. can we maybe just provide more guidance on how to menu more better?

**Comment by aschweigert** [comment]
@kaeti thoughts on this?

**Comment by kaeti** [comment]
Third tier revealed on click (with second tier shown by default)? 

Why are people monsters?

**Comment by benlk** [comment]
This has merge conflicts in the grunt-compiled CSS, but it's not conflicting in the LESS or in the JavaScript. It would be nice if GitHub detailed why it's unable to merge, since it merges cleanly on my machine.

screen shot 2015-05-22 at 6 17 46 pm

Here's a very, very long menu that has collapsed. 

1. The first-level menu items are displayed in the dropdown.
2. Second-level menu items, which would normally be displayed in a dropdown, are displayed indented.
3. The third level and following are hidden in Largo's previous menu CSS, so they are hidden here.

This menu is larger than the page is tall, so it overflows and scrolls vertically. There isn't any real indication of the scroll unless you happen to use the mousewheel or an equivalent gesture.

This does not affect display on mobile devices.

Questions:

- [ ] How should the scrollability be made visible?
- [ ] Are there any other style suggestions?

**Comment by benlk** [comment]
Closing this PR because @aschweigert, @rnagle and I decided that we wouldn't use this exact method of overflowing in Largo.

**Pull request closed without merging**
