### PR TITLE
A few more fixes for "load more posts" bugs

### PR DESCRIPTION
**Pull request by rnagle**
This fixes an issue where "load more posts" skips a variable number of posts on the category archive page.

Details:

- Changes `largo_get_featured_posts_in_category` so that it returns a predictable number of posts
- Uses only `largo_get_featured_posts_in_category` to populate the top of "featured" area of category archive pages
- Since `largo_get_featured_posts_in_category` is used to [filter category archives queries](https://github.com/INN/Largo/blob/c05aa73cfb587611a2ca7046e1975a3042c583df/inc/taxonomies.php#L301-L315), we can now be sure that the river on category archive pages will display the default number of posts set via the WordPress dashboard.
- Changes the LMP javascript to use a zero-indexed `paged` attribute (turns out `paged` is zero-indexed and `page` is one-indexed).

I would include tests but I don't have time right now.

### CODE REVIEW

**Comment by rnagle** [comment]
We'll probably want to merge this to the `master` branch since we'll want to deploy the change for our sites asap.

**Comment by benlk** [comment]
I'm happy that tests are currently passing, but also I'm concerned that tests were either not failing or that changing the functions here didn't cause tests to fail.

**Comment by benlk** [comment]
Note from today for tomorrow: This appears okay to deploy, with the matching commits for Chicago Catalyst form the staging branch of the umbrella.

**Comment by benlk** [comment]
Tested this on staging:

- Tags :+1: (MWEN)
- Author :+1: (MWEN)
- Category :+1: (MWEN)
- Homepage :+1: (Current, MWEN)
- Series 
    - NPQ http://nonprofitquarterly-org.largoproject.staging.wpengine.com/series/winter-2001/ returns out of order without a published, trashed or draft series landing page, but all posts are present.
    - INVW no LMP button on the 224-post http://invw-org.largoproject.staging.wpengine.com/series/dateline-earth/
    - Current loads in order without a series landing page http://current-org.largoproject.staging.wpengine.com/series/spectrum-auction/
    - Youth Today loads in order without a series landing page http://youthtoday-org.largoproject.staging.wpengine.com/series/available-grants/

**Comment by benlk** [comment]
Merging this because the NPQ and INVW problems do not appear to be Largo problems.

**Comment by benlk** [comment]
https://github.com/INN/Largo/commit/4f2890bcc08f6516f5df2dd24bc5220e9c5aa613

**Pull request closed without merging**
