### PR TITLE
Sticky nav menu dropdowns on touchscreen computers

### LINKED ISSUE #1368: Desktop sticky nav menu dropdowns don't drop down on larger touchscreens
This is true from 769px upwards.

screen shot 2016-10-28 at 12 15 23 pm

### PR DESCRIPTION
**Pull request by benlk**
This PR is a work in progress.

currently broken:
- in the mobile nav:
    - opening a second-level navbar item with the caret
    - clicking the top-level navbar item

## Changes

- Updates Modernizr JS library from 2.8.3 to 3.6.0
- The `navigation.js` enqueue now uses filemtime to provide the cachebuster.
- Mouse pointers can now trigger CSS `:hover` styles on our menu dropdowns on devices with touch support
- `.touch` and `.no-touch` classes are no longer applied by Modernizr, as Modernizr dropped support for that specific test with 3.0. https://modernizr.com/news/modernizr-3-new-release-site
- `.touch` and `.no-touch` are now applied by Largo's navigation.js, because the navigation-related code is the only place that Largo references those classes.
- the navigation `:hover` classes are not scoped to `.no-touch` anymore, nor are the `.open` navigation classes scoped to `.no-touch`

## Why

Updating Modernizr because our version is old and out of date; see the Modernizr issue where they deprecated the `Modernizr.touch` test because it wasn't testing what people expected it to test: https://github.com/Modernizr/Modernizr/issues/548

Fixes #1368 (hopefully)

### CODE REVIEW

**Comment by benlk** [comment]
Is there a way to determine what the target of the click is when the event listener is attached to `body`? If there was, we could determine if the click handler is the `open` element.

Maybe the click handlers should be declared in a different order?

**Comment by tylermachado** [comment]
I see in the comments here that we can't use preventDefault -- but I wonder if this is a case for `event.stopPropagation` ? https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

(Not sure if that would run into the same Chrome blocker; can't find it called out specifically the way the preventDefault issue is)

**Comment by benlk** [comment]
Yep, event.stopPropagation works, and I'm able to click on the parent of the dropdown, or on other nav elements.

Removing these items from the broken list:

> - `closeOpenMenu` currently affects all clicks on `<body>`, including the one that just opened the menu. So the event handler that opens the menu fires, the event handler that closes the menu fires: the tap appears to do nothing.
> - when that's fixed, make sure that tapping the top item of a dropdown does allow the link to be opened.


Not able to click on the dropdown itself, however. ☹️

**Comment by benlk** [comment]
fixed:
> 
- with an open dropdown, clicking a link in the dropdown closes it, not performs navigation.

Now it works on desktop, but that appears to have broke the phone nav: can't tap the caret to trigger the dropdown; can't click the top-level link that matches the caret.

**Comment by benlk** [comment]
Specifically broken in my testing: the second-level menu items in the mobile size of the sticky nav
: 
Screen Shot 2019-04-22 at 18 47 40

This occurs with
- Chrome set to "responsive" mode with touch screen emulation enabled.
- Chrome set to emulate a Nexus 5X
- Chrome set to emulate an iPhone X
- the iOS simulator for an iPhone X

**Comment by benlk** [comment]
So we've been having different experiences on different sites all running the same commit b9337892b825f689af72a3eb243806d1e03c141f of this branch. My hunch is that it's something in the theme options, which are stored in the `wp_options` table with the key `optionsframework`:

largo.test doesn't work:

```
a:25:{s:18:"show_donate_button";b:0;s:18:"show_header_social";b:0;s:19:"single_social_icons";b:0;s:17:"article_utilities";a:4:{s:8:"facebook";s:1:"0";s:7:"twitter";s:1:"0";s:5:"email";s:1:"0";s:5:"print";s:1:"0";}s:28:"single_floating_social_icons";b:0;s:15:"no_header_image";b:0;s:17:"show_sticky_posts";b:0;s:22:"hide_category_featured";b:0;s:17:"use_topic_sidebar";b:0;s:25:"use_before_footer_sidebar";b:0;s:18:"sticky_nav_display";b:0;s:21:"main_nav_hide_article";b:0;s:19:"show_dont_miss_menu";b:0;s:12:"less_enabled";b:0;s:14:"series_enabled";b:0;s:22:"custom_landing_enabled";b:0;s:19:"leaderboard_enabled";b:0;s:21:"header_widget_enabled";b:0;s:18:"post_types_enabled";b:0;s:18:"disclaimer_enabled";b:0;s:7:"use_gcs";b:0;s:16:"noindex_archives";b:0;s:15:"show_job_titles";b:0;s:2:"id";s:5:"largo";s:12:"knownoptions";a:1:{i:0;s:13:"largo_0_5_5_4";}}
```
```
Array
(
    [show_donate_button] => 
    [show_header_social] => 
    [single_social_icons] => 
    [article_utilities] => Array
        (
            [facebook] => 0
            [twitter] => 0
            [email] => 0
            [print] => 0
        )

    [single_floating_social_icons] => 
    [no_header_image] => 
    [show_sticky_posts] => 
    [hide_category_featured] => 
    [use_topic_sidebar] => 
    [use_before_footer_sidebar] => 
    [sticky_nav_display] => 
    [main_nav_hide_article] => 
    [show_dont_miss_menu] => 
    [less_enabled] => 
    [series_enabled] => 
    [custom_landing_enabled] => 
    [leaderboard_enabled] => 
    [header_widget_enabled] => 
    [post_types_enabled] => 
    [disclaimer_enabled] => 
    [use_gcs] => 
    [noindex_archives] => 
    [show_job_titles] => 
    [id] => largo
    [knownoptions] => Array
        (
            [0] => largo_0_5_5_4
        )

)
```

current.test does work:

```
a:70:{s:10:"site_blurb";s:0:"";s:8:"rss_link";s:26:"https://current.test/feed/";s:18:"show_donate_button";b:0;s:11:"donate_link";s:0:"";s:18:"donate_button_text";s:10:"Donate Now";s:13:"copyright_msg";s:43:"Copyright %d. Current. All rights reserved.";s:5:"ga_id";s:12:"UA-6017171-1";s:19:"posts_term_singular";s:4:"Post";s:17:"posts_term_plural";s:5:"Posts";s:13:"facebook_link";s:40:"https://www.facebook.com/currentpubmedia";s:12:"twitter_link";s:34:"http://twitter.com/currentpubmedia";s:12:"youtube_link";s:0:"";s:14:"instagram_link";s:0:"";s:13:"linkedin_link";s:0:"";s:11:"tumblr_link";s:0:"";s:14:"pinterest_link";s:0:"";s:11:"github_link";s:0:"";s:11:"flickr_link";s:0:"";s:18:"show_header_social";b:0;s:19:"single_social_icons";s:1:"1";s:17:"article_utilities";a:4:{s:8:"facebook";s:1:"0";s:7:"twitter";s:1:"0";s:5:"email";s:1:"0";s:5:"print";s:1:"0";}s:28:"single_floating_social_icons";s:1:"1";s:7:"fb_verb";s:5:"share";s:17:"logo_thumbnail_sq";s:68:"https://current.test/wp-content/uploads/2014/08/current_facebook.png";s:7:"favicon";s:60:"https://current.test/wp-content/uploads/2014/08/favicon1.ico";s:15:"no_header_image";b:0;s:15:"banner_image_sm";s:91:"https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_768px-1-336x108.jpg";s:16:"banner_image_med";s:89:"https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_980px-336x108.jpg";s:15:"banner_image_lg";s:85:"https://current.test/wp-content/uploads/2015/02/Current_logo_nobar_1170px-336x108.png";s:18:"sticky_header_logo";s:82:"https://current.test/wp-content/uploads/2015/03/CURRENT_logo_2018_notext_200px.jpg";s:13:"home_template";s:12:"HomepageBlog";s:17:"show_sticky_posts";s:1:"1";s:15:"homepage_bottom";s:4:"list";s:14:"num_posts_home";s:2:"10";s:9:"cats_home";s:5:"-4363";s:15:"single_template";s:7:"classic";s:22:"hide_category_featured";b:0;s:17:"use_topic_sidebar";b:0;s:25:"use_before_footer_sidebar";b:0;s:15:"custom_sidebars";s:62:"FCC Series Sidebar
Hearken Sidebar
Diversity Package Sidebar";s:13:"footer_layout";s:12:"3col-default";s:18:"sticky_nav_display";s:1:"1";s:21:"main_nav_hide_article";b:0;s:18:"nav_overflow_label";s:4:"More";s:17:"nav_alt_site_name";s:0:"";s:19:"show_dont_miss_menu";s:1:"1";s:15:"dont_miss_label";s:10:"Don't Miss";s:17:"footer_menu_label";s:11:"Current.org";s:12:"less_enabled";b:0;s:14:"series_enabled";s:1:"1";s:22:"custom_landing_enabled";s:1:"1";s:27:"landing_left_region_default";s:12:"sidebar-main";s:28:"landing_right_region_default";s:12:"sidebar-main";s:19:"leaderboard_enabled";s:1:"1";s:21:"header_widget_enabled";b:0;s:18:"post_types_enabled";b:0;s:13:"largo_version";s:5:"0.6.2";s:18:"disclaimer_enabled";b:0;s:18:"default_disclaimer";s:0:"";s:7:"use_gcs";s:1:"1";s:6:"gcs_id";s:33:"005087390703810785250:ldhvxxtbp8k";s:15:"twitter_acct_id";s:0:"";s:24:"google_site_verification";s:43:"Pycgplauq98cEooGwJm6CBm2mLTsG5FPCA4EAEQjegE";s:9:"fb_admins";s:9:"558646386";s:9:"fb_app_id";s:0:"";s:17:"fb_tracking_pixel";s:0:"";s:18:"bitly_verification";s:0:"";s:16:"noindex_archives";b:0;s:11:"404_message";s:0:"";s:15:"show_job_titles";b:0;}
```
```
(
    [site_blurb] => 
    [rss_link] => https://current.test/feed/
    [show_donate_button] => 
    [donate_link] => 
    [donate_button_text] => Donate Now
    [copyright_msg] => Copyright %d. Current. All rights reserved.
    [ga_id] => UA-6017171-1
    [posts_term_singular] => Post
    [posts_term_plural] => Posts
    [facebook_link] => https://www.facebook.com/currentpubmedia
    [twitter_link] => http://twitter.com/currentpubmedia
    [youtube_link] => 
    [instagram_link] => 
    [linkedin_link] => 
    [tumblr_link] => 
    [pinterest_link] => 
    [github_link] => 
    [flickr_link] => 
    [show_header_social] => 
    [single_social_icons] => 1
    [article_utilities] => Array
        (
            [facebook] => 0
            [twitter] => 0
            [email] => 0
            [print] => 0
        )

    [single_floating_social_icons] => 1
    [fb_verb] => share
    [logo_thumbnail_sq] => https://current.test/wp-content/uploads/2014/08/current_facebook.png
    [favicon] => https://current.test/wp-content/uploads/2014/08/favicon1.ico
    [no_header_image] => 
    [banner_image_sm] => https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_768px-1-336x108.jpg
    [banner_image_med] => https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_980px-336x108.jpg
    [banner_image_lg] => https://current.test/wp-content/uploads/2015/02/Current_logo_nobar_1170px-336x108.png
    [sticky_header_logo] => https://current.test/wp-content/uploads/2015/03/CURRENT_logo_2018_notext_200px.jpg
    [home_template] => HomepageBlog
    [show_sticky_posts] => 1
    [homepage_bottom] => list
    [num_posts_home] => 10
    [cats_home] => -4363
    [single_template] => classic
    [hide_category_featured] => 
    [use_topic_sidebar] => 
    [use_before_footer_sidebar] => 
    [custom_sidebars] => FCC Series Sidebar
Hearken Sidebar
Diversity Package Sidebar
    [footer_layout] => 3col-default
    [sticky_nav_display] => 1
    [main_nav_hide_article] => 
    [nav_overflow_label] => More
    [nav_alt_site_name] => 
    [show_dont_miss_menu] => 1
    [dont_miss_label] => Don't Miss
    [footer_menu_label] => Current.org
    [less_enabled] => 
    [series_enabled] => 1
    [custom_landing_enabled] => 1
    [landing_left_region_default] => sidebar-main
    [landing_right_region_default] => sidebar-main
    [leaderboard_enabled] => 1
    [header_widget_enabled] => 
    [post_types_enabled] => 
    [largo_version] => 0.6.2
    [disclaimer_enabled] => 
    [default_disclaimer] => 
    [use_gcs] => 1
    [gcs_id] => 005087390703810785250:ldhvxxtbp8k
    [twitter_acct_id] => 
    [google_site_verification] => Pycgplauq98cEooGwJm6CBm2mLTsG5FPCA4EAEQjegE
    [fb_admins] => 558646386
    [fb_app_id] => 
    [fb_tracking_pixel] => 
    [bitly_verification] => 
    [noindex_archives] => 
    [404_message] => 
    [show_job_titles] => 
)
```

**Comment by benlk** [comment]
```diff
1a2,3
>     [site_blurb] => 
>     [rss_link] => https://current.test/feed/
2a5,19
>     [donate_link] => 
>     [donate_button_text] => Donate Now
>     [copyright_msg] => Copyright %d. Current. All rights reserved.
>     [ga_id] => UA-6017171-1
>     [posts_term_singular] => Post
>     [posts_term_plural] => Posts
>     [facebook_link] => https://www.facebook.com/currentpubmedia
>     [twitter_link] => http://twitter.com/currentpubmedia
>     [youtube_link] => 
>     [instagram_link] => 
>     [linkedin_link] => 
>     [tumblr_link] => 
>     [pinterest_link] => 
>     [github_link] => 
>     [flickr_link] => 
4c21
<     [single_social_icons] => 
---
>     [single_social_icons] => 1
13c30,33
<     [single_floating_social_icons] => 
---
>     [single_floating_social_icons] => 1
>     [fb_verb] => share
>     [logo_thumbnail_sq] => https://current.test/wp-content/uploads/2014/08/current_facebook.png
>     [favicon] => https://current.test/wp-content/uploads/2014/08/favicon1.ico
15c35,44
<     [show_sticky_posts] => 
---
>     [banner_image_sm] => https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_768px-1-336x108.jpg
>     [banner_image_med] => https://current.test/wp-content/uploads/2015/02/CURRENT_logo_2018_nobar_980px-336x108.jpg
>     [banner_image_lg] => https://current.test/wp-content/uploads/2015/02/Current_logo_nobar_1170px-336x108.png
>     [sticky_header_logo] => https://current.test/wp-content/uploads/2015/03/CURRENT_logo_2018_notext_200px.jpg
>     [home_template] => HomepageBlog
>     [show_sticky_posts] => 1
>     [homepage_bottom] => list
>     [num_posts_home] => 10
>     [cats_home] => -4363
>     [single_template] => classic
19c48,52
<     [sticky_nav_display] => 
---
>     [custom_sidebars] => FCC Series Sidebar
> Hearken Sidebar
> Diversity Package Sidebar
>     [footer_layout] => 3col-default
>     [sticky_nav_display] => 1
21c54,58
<     [show_dont_miss_menu] => 
---
>     [nav_overflow_label] => More
>     [nav_alt_site_name] => 
>     [show_dont_miss_menu] => 1
>     [dont_miss_label] => Don't Miss
>     [footer_menu_label] => Current.org
23,25c60,64
<     [series_enabled] => 
<     [custom_landing_enabled] => 
<     [leaderboard_enabled] => 
---
>     [series_enabled] => 1
>     [custom_landing_enabled] => 1
>     [landing_left_region_default] => sidebar-main
>     [landing_right_region_default] => sidebar-main
>     [leaderboard_enabled] => 1
27a67
>     [largo_version] => 0.6.2
29c69,77
<     [use_gcs] => 
---
>     [default_disclaimer] => 
>     [use_gcs] => 1
>     [gcs_id] => 005087390703810785250:ldhvxxtbp8k
>     [twitter_acct_id] => 
>     [google_site_verification] => Pycgplauq98cEooGwJm6CBm2mLTsG5FPCA4EAEQjegE
>     [fb_admins] => 558646386
>     [fb_app_id] => 
>     [fb_tracking_pixel] => 
>     [bitly_verification] => 
30a79
>     [404_message] => 
32,38c81
<     [id] => largo
<     [knownoptions] => Array
<         (
<             [0] => largo_0_5_5_4
<         )
< 
< )
---
> )
\ No newline at end of file
```

**Comment by benlk** [comment]
Toggling the `sticky_nav_display` option doesn't affect this.

`WP_DEBUG` true or false also does not appear to affect this?

**Comment by benlk** [comment]
Correction: WP_DEBUG true/false did not affect the site I was looking at because LARGO_DEBUG was set, and in most enqueues the same effect is had.

```php
define( 'LARGO_DEBUG', false); // the thing works
define( 'LARGO_DEBUG', true); // the thing doesn't work
```

**Comment by benlk** [comment]
Okay, after running `grunt uglify`, the behavior is now consistent between `LARGO_DEBUG` values.

In this PR, at this commit:

- in the mobile nav (below about 768px), the following do not work:
    - opening a second-level navbar item with the caret
    - clicking the top-level navbar item

**Comment by benlk** [comment]
Would it make sense to copy the changes from https://github.com/INN/largo/pull/1662 into this?

**Comment by benlk** [comment]
No; let #1622 be its own PR.

**Pull request merged**
