### PR TITLE
Largo Social Icon Update

### PR DESCRIPTION
**Pull request by dryanmedia**
Ported from #769.

### CODE REVIEW

**Comment by rnagle** [comment]
This still isn't quite right. On a vanilla Largo install, here's what I'm seeing:

image

- The email icon obviously doesn't match the Twitter and Facebook ones. We should probably be consistent here.
- Also, the padding around the email icon is inconsistent/lopsided.

image

- This looks mostly good except that it should probably be aligned left by default.

Pinging @kaeti to get her opinion.

**Comment by kaeti** [comment]
Agree on align left.

For the email icon, agree that we should ditch background color and have it match style of other icons (we can use a gray for the non-social icons).

**Comment by aschweigert** [comment]
At various points we've been using circular icons (w/ bg color), square icons (w/ bg color) or colored icons w/o a bg color. Let's pick one and make sure it's implemented consistently.

**Comment by aschweigert** [comment]
Since we went with the circular icons in the footer i think we should probably just go with that. This will also affect the social icons in the header (and I think that's fine). Any objections?

**Comment by kaeti** [comment]
I'm fine with that, but it seems like having no background works best in most places (header, widgets, article page social features). And with the new footer styles, I think having the simplicity of just the icons would work fine.

**Comment by aschweigert** [comment]
So it shall be.

**Comment by rnagle** [comment]
Pulled in some updates from develop, resolved conflicts and made some adjustments. This is where we're at now:

image

image

**Comment by rnagle** [comment]
One last update on this before I start addressing affected child themes:

image

Adjustments to the footer:

image

**Comment by kaeti** [comment]
:+1:

**Comment by rnagle** [comment]
Merged this work in `develop` around 69be91de3e837e5fa29c4d705dbc66b354382366.

**Pull request closed without merging**
